### ISSUE TITLE
Possible typo in PAPPL code

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#103]
**Describe the bug**
In the file `pappl/system-loadsave.c`, in the function `papplSystemLoadState()`, in the part where default settings for printers are loaded, you have the lines:
```
          snprintf(defname, sizeof(defname), "%s-default", line);
          snprintf(supname, sizeof(supname), "%s-default", line);
```
Should it not be
```
          snprintf(defname, sizeof(defname), "%s-default", line);
          snprintf(supname, sizeof(supname), "%s-supported", line);
```

**Comment by michaelrsweet** [comment]
Yes.

[v1.0.x e29c9ec] Fix loading of vendor defaults (Issue #103)
[master 0d4eb45] Fix loading of vendor defaults (Issue #103)
