### ISSUE TITLE
Add mention to libusb as build input

### ISSUE THREAD

**Issue by jonringer** [michaelrsweet/pappl#105]
**Describe the bug**
It's detailed in the .pc file:
```
Requires: @PKGCONFIG_GNUTLS@ @PKGCONFIG_LIBJPEG@ @PKGCONFIG_LIBPNG@ @PKGCONFIG_LIBUSB@ zlib >= 1.0
```
but not mentioned in readme.md or build.md

noticed when packaging it for nixpkgs: https://github.com/NixOS/nixpkgs/pull/107009

**Comment by michaelrsweet** [comment]
Now how did I miss *that*. Thanks for the catch!

**Comment by michaelrsweet** [comment]
[master 0c52f7c] Update README + BUILD files for libusb mentions (Issue #105)
