### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/pappl#114]
I would like to point out that an identifier like “[`_PAPPL_BASE_H_`](https://github.com/michaelrsweet/pappl/blob/17896d44e7325c079576f100e3d21cac55457c8c/pappl/base.h#L10 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by michaelrsweet** [comment]
No.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
