### ISSUE TITLE
PAPPL on Windows support

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/pappl#116]
The current PAPPL implementation is almost ready for use on Windows. Changes that are needed include:

- [x] Implement wrapper types/functions for POSIX threading APIs
- [x] Determine replacements for signal handling

A parallel issue regarding the pthread function calls was brought up by @elfring in #113 - basically the pthread_mutex and pthread_rwlock APIs return a status code when locking, but the current code does not check the return values. When implementing the wrapper functions, the POSIX locking APIs should also be wrapped to support retries and potentially an abort if the unthinkable occurs.

**Comment by elfring** [comment]
>Implement wrapper types/functions for POSIX threading APIs

How do you think about to [use the current support for multi-threading by the C programming language](https://en.cppreference.com/w/c/thread "Documentation for the thread support library")?

**Comment by michaelrsweet** [comment]
@elfring This C11 API is not widely implemented and there is no support for a native reader-writer lock, having likely been limited to what Microsoft could easily support...

**Comment by elfring** [comment]
:crystal_ball: I assume that your relationships can reduce undesirable software limitations another bit, can't they?

**Comment by michaelrsweet** [comment]
@elfring Huh?

**Comment by michaelrsweet** [comment]
[master 0233ca4] Initial implementation of POSIX threading functions needed for PAPPL on Windows (Issue #116)
