### ISSUE TITLE
_papplJobProcessRaster() does not support multiple copies

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#117]
Looking into the code of the `_papplJobProcessRaster() ` it seems that it does not support multiple copies.

How am I supposed to make a Printer Application print the number of copies the user requests and also to collate the copies if the user asks for it?

**Comment by michaelrsweet** [comment]
@tillkamppeter Raster streams are explicitly defined as not supporting collated copies, so clients send multiple copies of the Raster data when printing.

**Comment by tillkamppeter** [comment]
So not only collated copies but number of copies in general is not supported by Raster streams?
So on a typical Linux system with printer drivers provided by Printer Applications CUPS (with the `pdftopdf` filter) is taking care of multiple copies and collated copies?

**Comment by michaelrsweet** [comment]
@tillkamppeter Correct, it is up to the client to produce the copies, and all of the CUPS raster filters support this (and have since the beginning) since most raster printers lack the memory needed to produce copies on their own.
