### ISSUE TITLE
Manual tray handling

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#119]
Some printers have a manual feed tray (on PostScript printers this tray is usually also listed in the PPD file). Such a tray seems not to be supported at all in PAPPL.
It seems to be correct that it gets skipped when the "Media" page is displayed, as it is not loaded with a fixed type of paper, but there should be a way to get note of its presence somehow and to print a job from it.

Or one could perhaps even list it in "Media" as some users abuse it as a standard tray and keep some less frequently used paper type loaded on it. But then there should be a checkbox in the line for the manual tray on the "Media" page, named for example "Permanently loaded" and only when checked one can set the loaded paper for it,

**Comment by michaelrsweet** [comment]
@tillkamppeter By definition, the 'manual' source CANNOT have ready media - it always requires user intervention. The 'by-pass-tray' (usually called a "multi-purpose tray") *can* have ready media, and typically this physical tray shows up twice - once as manual to pause printing and once as a regular tray to pull the pre-loaded media.

**Comment by tillkamppeter** [comment]
Is the presence of a manual tray advertised via IPP, in the Printer Application's response to a client's get-printer-attributes IPP request? Does the manual tray get auto-selected by the Printer Application if a job requests a paper size not loaded in any of the standard trays?

**Comment by michaelrsweet** [comment]
The "media-source-supported" attribute lists 'manual', the "media-col-database' attribute may list the 'manual' source for any media sizes that are unique to it, and the "printer-input-tray" attribute will have a value corresponding to it.

**Comment by michaelrsweet** [comment]
OK, I don't think there is anything for me to do here - "manual" doesn't have ready media, "by-pass-tray" may. PAPPL supports both.
