### ISSUE TITLE
SEGV in pappl_snmp_find because cur_device->uri is NULL

### ISSUE THREAD

**Issue by prlw1** [michaelrsweet/pappl#121]
Just managed to compile ps-printer-app. Ran "ps-printer-app server", and "ps-printer-app devices". (No configuring had happened.) This gave me a SEGV in device-network.c
```
   843      if (!strcmp(make, "HP") && !strncmp(model, "HP ", 3))
   844        snprintf(info, sizeof(info), "%s (Network Printer %s)", model, cur_device->uri + 7);
   845      else
   846        snprintf(info, sizeof(info), "%s %s (Network Printer %s)", make, model, cur_device->uri + 7);
```
because
```
(gdb) print cur_device->uri
$3 = 0x0
```
Could be because I didn't configure any devices, but we probably shouldn't dump core as a result...

**Comment by michaelrsweet** [comment]
@prlw1 Hmm, we should never do the callback if the URI isn't filled in. Investigating...

**Comment by michaelrsweet** [comment]
[master a47b0eb] Fix crash from partially discovered SNMP printer (Issue #121)
