### ISSUE TITLE
Debian: ./testpappl fails with avahi_client_get_host_name_fqdn Assertion `client' failed

### ISSUE THREAD

**Issue by OdyX** [michaelrsweet/pappl#129]
While building pappl for Debian, I get blocked when running the build-time tests
```
./testpappl -c -l testpappl.log -L debug -o testpappl.output -t jpeg testpappl: client.c:771: avahi_client_get_host_name_fqdn: Assertion `client' failed.
```

This is when run in `pbuilder`, without avahi-daemon nor CUPS (?) installed. It also fails on Debian's Gitlab CI pipelines; https://salsa.debian.org/printing-team/pappl/-/jobs/1347207

Any idea in which direction to look at?

**Comment by michaelrsweet** [comment]
OK, if avahi-daemon is not present then all of the DNS-SD stuff won't work and won't be testable. It shouldn't crash, however, so that is a bug to fix.

**Comment by michaelrsweet** [comment]
[master 779ba61] Handle when the Avahi daemon is not running (Issue #129)
[v1.0.x 59f6e03] Handle when the Avahi daemon is not running (Issue #129)

**Comment by OdyX** [comment]
That works, thanks!
