### ISSUE TITLE
manpages have groff warnings

### ISSUE THREAD

**Issue by OdyX** [michaelrsweet/pappl#136]
**Describe the bug**
`lintian` Debian linting tool shows manpage formatting warnings:
```
groff-message usr/share/man/man3/pappl-client.3.gz 235: warning: macro 'IN' not defined
groff-message usr/share/man/man3/pappl-device.3.gz 275: warning: macro 'IN' not defined
groff-message usr/share/man/man3/pappl-job.3.gz 156: warning: macro 'aborted-by-system'' not defined (possibly missing space after 'ab')
groff-message usr/share/man/man3/pappl-job.3.gz 160: warning: macro 'compression-error'' not defined
groff-message usr/share/man/man3/pappl-job.3.gz 164: warning: macro 'document-format-error'' not defined (possibly missing space after 'do')
groff-message usr/share/man/man3/pappl-job.3.gz 168: warning: macro 'document-password-error'' not defined (possibly missing space after 'do')
…
```

I'm by far not a (g)roff expert, but It seems that single quotes (') mark macro starters, and need escapes. I also haven't determined whether this is a direct formatting issue in `man/pappl-job-body.man` or in codedoc.

**Comment by michaelrsweet** [comment]
@OdyX Looks like something I need to fix in codedoc...

**Comment by michaelrsweet** [comment]
[codedoc issue #12](https://github.com/michaelrsweet/codedoc/issues/12) will fix the generator issue, then I'll re-gen the documentation files here.

**Comment by michaelrsweet** [comment]
[master d369af3] Update man pages with new codedoc quoting (Issue #136)
