### ISSUE TITLE
Web Interface: On "Printing Defaults" page "Borderless" state of media is not shown

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#138]
In the PostScript Printer Application I have set up my HP OfficeJet Pro 8730 with two trays. After having selected that Tray 2 is present under "Device Settings" I set the loaded media under "Media" as follows:
```
   Tray 1 Media:  A4  [X] Borderless  Plain Paper
   Tray 2 Media:  A4  [ ] Borderless  Plain Paper
```
Now I switch to "Printing Defaults" and in the selector for the paper tray I get the two choices:
```
A4 (Plain Paper) from Tray 1
A4 (Plain Paper) from Tray 2
```
So here one cannot see the difference of the two loaded media. What I expect is something like:
```
A4 (Plain Paper, Borderless) from Tray 1
A4 (Plain Paper) from Tray 2
```

**Comment by michaelrsweet** [comment]
[master c0e9b00] Report borderless state of media (Issue #138)

[v1.0.x 9f11ef7] Report borderless state of media (Issue #138)
