### ISSUE TITLE
Printer Application server running as root not accessible for users

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#148]
I want to run the PostScript Printer Application in a Snap, the Snap auto-starting the Printer Application via `daemon: simple` in the `snapcraft.yaml`. This makes the Printer Application server running as root, which is as designed in the Snap world, system daemons run as root. I can, as any normal user, without problems add and configure printers and add user PPD files via the web interface, and I can print with CUPS using CUPS' temporary queues for IPP printers.

What does not work is using `ps-printer-app` for client operations (with subcommands "printers", "jobs",...) as a normal user, only as root `ps-printer-app` works as a client, but as normal user the problem is not a "Permission denied" but the server is simply not found. Even worse is that one does not simply get an error message but the client `ps-printer-app` starts another, personal server for the user leading to complete confusion (another bug, issue #149).

The problem is how the socket file name is created: The internal function `_papplMainloopGetServerPath()` takes the environment variable `TMPDIR` and in this directory a file named by the Printer Application itself with the **user ID of the caller** added and the extension `.sock`.

Now in my Snap environment the server is running as root, for making the printer available system-wide. The client instances of `ps-printer-app` are run by normal users and so they use a socket file name with the calling user's user IDs, and not the same as the server.

So what I want to ask for is that either
- the socket file name can be supplied by a command line option or environment variable, this I could supply in the wrapper script `scripts/run-ps-printer-app`.
- at build time one can choose between a user/developer mode (current behavior) and a system mode (socket file name without user ID)

**Comment by tillkamppeter** [comment]
This patch solves the problem:
[pappl-system-wide-server-socket-support.patch.txt](https://github.com/michaelrsweet/pappl/files/5961302/pappl-system-wide-server-socket-support.patch.txt)
If a client does not find a server under the user's socket name, it tries root's socket name (for a system-wide server with user ID 0), and only if this also fails it fires up its own server.

**Comment by michaelrsweet** [comment]
@tillkamppeter I'll take a look at the patch. Trying the root socket is a good idea.

**Comment by michaelrsweet** [comment]
[master b88be1a] Address persistence and a system-wide server (Issue #128, Issue #148)
