### ISSUE TITLE
If Printer Application called as a client and does not find the server, it fires up its own server

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#149]
Situation is as described in issue #148, Printer Application runs as server by root, auto-started by the installed Snap of the Printer Application, to make printers available system-wide.

As described in issue #148, the Printer Application run as client (with subcommands "printers", "jobs",...) by a normal user to do operations on the running server, does not find the server, but instead of simply giving an error message and exit, they fire up another, private server.

Here I would like to have one or more of these solutions:
- The Printer Application run by the user with a client operation not finding a server of that user should check whether there is a system-wide server and direct the operation to that one then.
- There should be a way to configure whether auto-starting of a server is desired, ideally both by a build-time option for the default and a command line option/environment variable (which could be added by the Snap's wrapper script for example).

In a system-wide-server environment auto-starting of a server by a client operation should really not happen.

**Comment by michaelrsweet** [comment]
@tillkamppeter The auto-start of server is an intentional feature. There isn't a way to disable it.
