### ISSUE TITLE
Cannot set default printer with the web interface

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#150]
When I run the command (a `ps-printer-app` server is running and printers got added via the web interface)
```
ps-printer-app jobs
```
I get the error message
```
ps-printer-app: No default printer available.
```
This means that PAPPL has the concept of a default printer, but the web interface has no way to set a defaut printer nor a way to show which printer is the current default printer.

**Comment by michaelrsweet** [comment]
[master b99b30e] Set as default button for web interface (Issue #150)
