### ISSUE TITLE
Extend "ps-printer-app drivers" to also show supported device IDs

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#157]
We have discussed automated printer setup and guiding users to the correct Printer Application on the [OpenPrinting Mailing list](https://lists.linuxfoundation.org/pipermail/printing-architecture/2021/thread.html) in the thread ["Automatic printer setup with Printer Applications"](https://lists.linuxfoundation.org/pipermail/printing-architecture/2021/003934.html) and came to the conclusion that there should not be conducted an automatic setup for printers by individual Printer Applications, but instead, a central system tool should guide the user to find the Printer Application which he needs for his printer.

For this it would be useful to find out which printer models each Printer Application supports. Calling
```
$ ps-printer-app drivers
```
gives a list of all contained drivers, with machine-readable name and human-readable description:
```
generic                                 Generic PostScript Printer
brother--dcp-7025--en                   Brother DCP-7025 (en)
brother--dcp-7045-n--en                 Brother DCP-7045N (en)
brother--dcp-8020--en                   Brother DCP-8020 (en)
brother--dcp-8025-d--en                 Brother DCP-8025D (en)
brother--dcp-8040--en                   Brother DCP-8040 (en)
brother--dcp-8045-d--en                 Brother DCP-8045D (en)
[...]
```
Problem is here that one does not have information about which printer models are supported, especially as driver names and descriptions do not always contain the model names. Therefore it would be great to have also the device IDs in the list, as already suggested [here](https://lists.linuxfoundation.org/pipermail/printing-architecture/2021/003950.html).

This could be either simply added, so that the `drivers` subcommand always shows a table with three columns, the last one being the device ID, or we introduce a modifier option for the `drivers` subcommand which adds this column.

**Comment by tillkamppeter** [comment]
There should also be distinction between dedicated and generic support, the former meaning model-specific support which supports all or at least most functionality of the printer (like a manufacturer-supplied PPD in the PostScript Printer Application) and the latter meaning to make the printer working via some standard property, as doing PostScript, PCL 5c/e, ... (like the "Generic PostScript printer" entry in the PostScript Printer Application).

A forth column could tell whether the support is generic or dedicated. A modifier option could also make all/generic-only/dedicated-only being shown.

**Comment by michaelrsweet** [comment]
@tillkamppeter I think it should be sufficient to just define the make "Generic" as a placeholder for this, e.g. "Generic PCL Laser Printer", "Generic PostScript Printer", etc. with no "MFG" or "MANUFACTURER" key in the device ID.
