### ISSUE TITLE
Add subcommand to simply ask whether a given printer is supported

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#158]
In issue #157 I already mentioned that we want to create a tool to guide the user to find the correct Printer Application for his printer. To facilitate this, it would be great to have a subcommand like this:
```
$ ps-printer-app is-supported SEARCH_TERM
```
where `SEARCH_TERM` can be a make/model string or device ID:
```
$ ps-printer-app is-supported 'HP OfficeJet Pro 8730'
$ ps-printer-app is-supported 'MFG:HP;MDL:HP OfficeJet Pro 8730;CMD:PCL5c,PCLXL,POSTSCRIPT,NATIVEOFFICE,PDF,PCL3GUI,PCL3,PJL,Automatic,JPEG,PCLM,AppleRaster,PWGRaster,802.11,802.3,DESKJET,DYN;CLS:PRINTER;DES:D9L20A;'
```
One could call the auto-add callback function and if it returns a driver name, return this driver name and exit with 0, if it does not return a driver name (unsupported printer) return nothing and exit with 1.

This function should not run device discovery nor poll information from a device, so that it returns quickly and is independent of whether the device actually exists and whether it is connected.

**Comment by tillkamppeter** [comment]
There should also be distinction between dedicated and generic support, the former meaning model-specific support which supports all or at least most functionality of the printer (like a manufacturer-supplied PPD in the PostScript Printer Application) and the latter meaning to make the printer working via some standard property, as doing PostScript, PCL 5c/e, ... (like the "Generic PostScript printer" entry in the PostScript Printer Application).

There could be different exit code, 0 for dedicated, 1 for generic, and 2 for no support.

**Comment by michaelrsweet** [comment]
@tillkamppeter Using exit codes isn't viable for a number of reasons. Returning the driver name and the 1284 device ID that matches is probably the best approach and allows the caller to determine how good the match is (and would match how "drivers" will work...)
