### ISSUE TITLE
Mopria app allows to print test page for CUPS printer but not for PAPPL Printer Application

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#160]
To test how well driverless printing **as a server** works, I am running the Mopria app on my Google Pixel 5 (Android 11). With today's state-of-the-art of CUPS on its OpenPrinting GIT repository CUPS' shared printers are made available in a Mopria-compatible way and are listed by the app. At the bottom of the screen appears "PRINT TEST PAGE" and tapping there makes the test page being printed.

Also PAPPL-based Printer Applications share printers so that the Mopria app lists them. I have the PostScript Printer Application running and two printers set up in it. PAPPL lists them, and on the printer pages also appear the media-ready settings, but there does not appear "PRINT TEST PAGE". And I have implemented test page printing in the PostScript Printer Application.

**Comment by michaelrsweet** [comment]
The test page functionality from Mopria has nothing to do with whether you have provided a test page callback in PAPPL. I will determine what Mopria is looking for WRT a test page.

**Comment by michaelrsweet** [comment]
@tillkamppeter I just tested from my Pixel 4 to the testpappl Office Printer and it came through just fine.

**Comment by michaelrsweet** [comment]
And FWIW it just prints a PDF or PWG Raster file. Not sure what your ps-printer-app is reporting for supported formats, perhaps it is confused?

**Comment by tillkamppeter** [comment]
A typical DNS-SD record of the PostScript Printer Application is the following (for a printer named "test"):
```
Service Type: _ipp._tcp
Service Name: test
Domain Name: local
Interface: enx8c47be090292 IPv4
Address: till-x1yoga.local/10.0.0.39:8000
TXT Scan = F
TXT PaperMax = legal-A4
TXT Fax = F
TXT product = (HP OfficeJet Pro 8730 Postscript - Query)
TXT mopria-certified = 1.3
TXT priority = 0
TXT qtotal = 1
TXT txtvers = 1
TXT Duplex = T
TXT Color = T
TXT TLS = 1.2
TXT URF = V1.4,W8,SRGB24,PQ3-4-5,DM1,FN3,IS20-21,MT1-4-6,OB10,RS600
TXT UUID = f0d2a912-09ab-3a35-6b66-3f3ab6a21a7a
TXT pdl = image/pwg-raster,image/urf,application/vnd.printer-specific,application/pdf,application/postscript,image/jpeg,image/png
TXT note = 
TXT adminurl = http://till-x1yoga.local:8000/test/
TXT ty = HP OfficeJet Pro 8730 Postscript - Query
TXT rp = ipp/print/test
```
The advertised PDLs contain both PDF and PWG Raster.

**Comment by tillkamppeter** [comment]
I have checked again and now the Mopria app gives a test page button also on the printers of the PostScript Printer Application.
