### ISSUE TITLE
papplSystemIteratePrinters test fails under ARM

### ISSUE THREAD

**Issue by OdyX** [michaelrsweet/pappl#162]
The papplSystemIteratePrinters test fails in Debian ARM (armel, armhf) builds; 1.0.2 was uploaded to Debian experimental, and the builds failed on these architectures:

- [armel build log](https://buildd.debian.org/status/fetch.php?pkg=pappl&arch=armel&ver=1.0.2-1&stamp=1618163503&raw=0)
- [armhf build log](https://buildd.debian.org/status/fetch.php?pkg=pappl&arch=armhf&ver=1.0.2-1&stamp=1618163383&raw=0)

([It also fails on PowerPC, but with a different error;  ](https://buildd.debian.org/status/fetch.php?pkg=pappl&arch=powerpc&ver=1.0.2-1&stamp=1618164490&raw=0)).

I have not tried to determine whether the test (introduced in 1.0.2) fails in 1.0.1; in other words; was it always broken, or is the breakage only visible now?

**Comment by michaelrsweet** [comment]
@OdyX I've seen this sporadically on the Github Actions build hosts as well, although it hasn't been reproducible.

1.0 and 1.0.1 didn't have the full API test suite that 1.0.2 has, so it probably lay dormant in prior releases.

**Comment by michaelrsweet** [comment]
Found some more threading issues, and I think this should resolve things once and for all!

[master 1d55a26] Fix some more threading issues (Issue #155, Issue #162)

[v1.0.x b9cdc23] Fix some more threading issues (Issue #155, Issue #162)
