### ISSUE TITLE
When printer not available queue pauses and job cannot get canceled

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#163]
I am using the PostScript Printer Application and have created a print queue for my USB-connected HP OfficeJet Pro 8730. Then I have unplugged the USB and clicked the button for printing a test page in the web interface.

The job stays in the queue, and the printer gets stopped according to the web interface. I click on "Cancel" at the job entry and confirm on the next screen. The job entry shows "Canceling" now but the canceling of the job never completes. It stays this way for arbitrarily long time. Also the "Cancel all jobs" butoon at the top of the list does not help. The job stays with "Canceling".

I am even not able to shut down the Printer Application. It stays running, probably waiting for the job to go away somehow (in the Snap systemd probably does a `kill -9` after some timeout).

What is missing here is
- Job cancelation should always immediately cancel the job, even if one cannot communicate with the printer (the user could have sent the job to another printer and wants to cancel it here).
- Also shutdown should always work, even if there is a stopped queue or a job waiting for a printer to re-appear.
- There should be buttons to stop and start a printer
- There should also be a button to move the job to another queue
- There should be also subcommands for the operations I mentioned here

Log file of the hanging job: 
[ps-printer-app-20210420.log.txt](https://github.com/michaelrsweet/pappl/files/6346847/ps-printer-app-20210420.log.txt)

Only the few lines near the end of the log are important.

**Comment by tillkamppeter** [comment]
Also deleting the printer is not possible, it says "Printer is currently active". It should also be possible to delete a printer with hanging jobs.

**Comment by tillkamppeter** [comment]
When re-connecting the printer the cancelation of the job completes. It should be possible to cancel jobs also without the printer coming back to life.

**Comment by tillkamppeter** [comment]
Seems that when on the re-connection of the printer the cancelation completes the printer receives a zero-page job, as it makes the noise of having received data. One sees this also in the log.

New version of log, with printer removal attempt and re-connection of the printer: 
[ps-printer-app-20210420-2.log.txt](https://github.com/michaelrsweet/pappl/files/6346919/ps-printer-app-20210420-2.log.txt)

**Comment by michaelrsweet** [comment]
[master d5a10ee] Add checks for canceled jobs and deleted printers when initially connecting to the printer for a job (Issue #163)

**Comment by tillkamppeter** [comment]
Your change gives at least a partial improvement. If I print to a printer which is turned off and right after realizing this I cancel the job, the job gets actually cancelled. But if I do not cancel the job and shut down the Printer Application (does not matter whether via the `kill` command or via a client using the `shutdown` sub-command) the shutdown is delayed by several minutes and the jobs are still there after a restart. Then I cannot cancel them, they go, as before, into "Canceling" state eternally and stay that way also after another restart. As before, now they only can be removed by hand-editing the state file.

I also asked for some additional buttons for the web interface, should I create a new issue for that?

**Comment by michaelrsweet** [comment]
@tillkamppeter OK, it sounds like I also need to check the system state in the loop...

**Comment by tillkamppeter** [comment]
Said jobs which get stuck "Canceling" are saved in the state file with `state="5"` and no state reason. After restarting the Printer Application they appear as "Processing" in the web interface and have a "Cancel" button again. Clicking "Cancel" brings them back into eternal "Canceling" state.

**Comment by michaelrsweet** [comment]
This should fix the shutdown hang and bogus job state in the history:

[master 176be96] Shutdown while trying to connect to printer hangs (Issue #163)

WRT instant cancellation, that simply isn't possible. Timely cancellation, yes, but not instant.

WRT adding a button or a subcommand to move jobs between printers, I'm not going to add that - it introduces a lot of weirdness (different capabilities, etc.) and makes IPP conformance harder (even what CUPS does isn't conforming...)

WRT start/stop buttons, you already filed another bug, which we'll use to track that feature request.
