### ISSUE TITLE
broken link - PAPPL web site

### ISSUE THREAD

**Issue by Waxhaw** [michaelrsweet/pappl#166]
From this link:  https://www.msweet.org/pappl/

The following section shows...

Documentation and Examples
Documentation can be found in the “doc” and “man” directories.

The OpenPrinting group has written a tutorial showing how to migrate the rastertohp driver from CUPS to a Printer Application using PAPPL, which can be used as a recipe for migrating any CUPS driver. This example is available in the `hp-printer-app project` and is also discussed in the PAPPL documentation.

The hp-printer-app project is a hyperlink that points to:  https://github.com/michaelsweet/hp-printer-app
and that gives a 404.

Just a heads up.  I thought you would want to know.

Cheers,

Ed

**Comment by michaelrsweet** [comment]
@Waxhaw Thanks, I've pushed the obvious fix.
