### ISSUE TITLE
Web Interface: Default printer should be more visible

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#182]
After selecting a printer as default printer by clicking "Set as Default" in the web interface it is difficult/unintuitive for users to see which of the printer is actually the default printer. I also had to look twice until I have seen that the "Set as Default" of my selected default printer has gone away.

There should be more visible than only a missing "Set as Default" button. Either the printer marked with the words "Default Printer" somewhere easily visible or at the top of the list "Default Printer: ...".

**Comment by michaelrsweet** [comment]
[master d493c5e] Add indicator for default printer (Issue #182)
