### ISSUE TITLE
Add API to create printer temporary files (test pages, etc.)

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#186]
To allow printing a test page via the test page button in the web interface there is an interface for a test page callback function. The function returns a file name of the file which contains the test page. This file simply gets printed like a regular print job.

This works well if one includes a static test page in the Printer Application, which is the same for all supported printers. If all supported printers have more or less the same page sizes this is not a big problem.

But sometimes one wants to have a dynamic test page, containing information about the printer, or adapted to the printer type. A good example is the 20+-year-old PostScript test page of CUPS, which prints a frame exactly at the non-printable margins and so shows whether the margin info of the driver is correct. Therefore I have revived this page in the PostScript Printer Application and in Printer Applications using Ghostscript. The input file is static and therefore it works with current test page callback, but the file is a PostScript program, executed by Ghostscript or by the printer. Any further or similar development would require PostScript programming and Printer Applications would need Ghostscript.

My idea is that the callback function could generate a test page. It gets the printer data structure, so it can find out about printer properties, like page size, margins, resolution, color, model name, .... It would write the test page into a temporary file and return the name of the file. Problem here is that the caller does not remove the test page after printing and so the generated test pages would fill up the disk.

My suggestion here would be to add a boolean output argument ("`bool *temporary`") to the call scheme of the test page callback and if the callback creates a temporary test page file, it sets this argument to "true", so that the caller knows that it has to delete the file after printing it. With a static test page file, this argument is set to false, so that the caller does not delete it.

An alternative, to avoid an API change, would be that PAPPL deletes the test page file after printing when it is in the temporary directory (`getenv("TMPDIR")`) and keep it otherwise.

**Comment by michaelrsweet** [comment]
[master 338ce97] Implement papplCreateTempFile and papplPrinterOpenFile APIs (Issue #186)
