### ISSUE TITLE
IPP notifications support

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/pappl#191]
Add support for [IPP notifications](https://datatracker.ietf.org/doc/html/rfc3995) and the [ippget notification method](https://datatracker.ietf.org/doc/html/rfc3996). Add a callback mechanism as well for a program to intercept events.

**Comment by tillkamppeter** [comment]
`make install` does not install the new `subscription.h` file, I have to manually install it when building Snaps using the current PAPPL.

**Comment by michaelrsweet** [comment]
@tillkamppeter Please don't build production snaps against the master branch, as that is the active development branch and is not intended for such usage. Pull from the v1.1.x branch if you want "bleeding edge stable" or use one of the release tarballs.

**Comment by michaelrsweet** [comment]
Primary coding complete, just need to finish up the unit tests.

**Comment by michaelrsweet** [comment]
All done!
