### ISSUE TITLE
Support for StatusUI Optionality on macOS

### ISSUE THREAD

**Issue by sjoubani** [michaelrsweet/pappl#201]
**Is your feature request related to a problem? Please describe.**
Given the web-based interface, it would be helpful to allow the StatusUI feature on macOS to be optional. Currently if compiled as-is, running as a LaunchDaemon results in failure to launch, presumably because the AppKit initialization fails.

**Describe the solution you'd like**
It would be helpful to have this as a `-o OPTION=VALUE` configuration

**Describe alternatives you've considered**
Changing the condition in `mainloop-subcommands.c:783` fixes the issue temporarily.

**Additional context**
Running pappl 1.2rc1, hp-printer-app `5fb3e4`, on macOS Monterey 12.3.1

**Comment by michaelrsweet** [comment]
@sjoubani Can't make it an option, but it should be able to gracefully fall back on non-GUI operation. Can you attach the crash report?

**Comment by sjoubani** [comment]
It doesn't seem to crash, but launchd reports `Service exited with abnormal code: 1`, then throttles the respawn as it gets stuck in a loop.

**Comment by sjoubani** [comment]
FYI, I tend to run network services as nobody(-1) to limit their privileges, but since patching my copy this isn't urgent.

**Comment by michaelrsweet** [comment]
[master 7fb20a8] Check that current UID is not 0 (root) or negative (nobody or other special accounts) before using the menubar extra UI (Issue #201)

**Comment by sjoubani** [comment]
I believe the definitive C API is to call `getaudit_addr(2)` from `bsm/audit.h` and check for the `AU_SESSION_FLAG_HAS_GRAPHIC_ACCESS` flag from `bsm/audit_session.h`, but I'm not a Darwin expert

**Comment by michaelrsweet** [comment]
@sjoubani Good catch, I agree this is the right API for the job and more reliable than simply keying off the UID.

[master bd8cfe5] Use getaudit_addr to determine whether we have GUI access on macOS (Issue #201)

**Comment by michaelrsweet** [comment]
Still dealing with some entitlement/code signing issues when running from an application bundle (necessary to get a proper icon in the menubar)...

**Comment by sjoubani** [comment]
Depending what you'd like to cover, I tend to use `NSBundle`. `NSBundle.mainBundle` should return nil for `-principalClass` if not an app, but `-infoDictionary` should still work for binaries if __TEXT,__info_plist exists (a good idea if codesigning is important). For the icon, `-bundleURL` (app) or `-executableURL` (binary) then `-getResourceValue:forKey:error:` with `NSURLEffectiveIconKey` should be sufficient.
