### ISSUE TITLE
Always false condition in `pappl/system.c`

### ISSUE THREAD

**Issue by qarmin** [michaelrsweet/pappl#205]
https://github.com/michaelrsweet/pappl/blob/97d7297ee47a21597b19791ccb660da27513db29/pappl/system.c#L594-L601

if `system->num_clients < system->max_clients` is true then opposite condition is always false

**Comment by michaelrsweet** [comment]
Hmm, looks like a copy/paste error. The intent is to restore listening for new connections once the number of clients goes below the preset limit.

**Comment by michaelrsweet** [comment]
[master e47214d] Fix max-clients code that re-enables listening (Issue #205)
