### ISSUE TITLE
Possible null pointer usage in `snmp.c`

### ISSUE THREAD

**Issue by qarmin** [michaelrsweet/pappl#206]
https://github.com/michaelrsweet/pappl/blob/97d7297ee47a21597b19791ccb660da27513db29/pappl/snmp.c#L289-L292

Community variable is used in `_PAPPL_DEBUG`, but later is checked if is null

**Comment by michaelrsweet** [comment]
Modern C doesn't care about this and will output "(null)" for a NULL string pointer. But I can add a NULL check here to silence any warnings. (Keep in mind this is DEBUG code and never used in a production build...)

**Comment by michaelrsweet** [comment]
[master 785a77c] Add NULL check in debug printf - not necessary but silences warning (Issue #206)
