### ISSUE TITLE
Index check should happen before using index

### ISSUE THREAD

**Issue by qarmin** [michaelrsweet/pappl#207]
This may not be a bug, but Cppcheck complains about it

https://github.com/michaelrsweet/pappl/blob/97d7297ee47a21597b19791ccb660da27513db29/pappl/snmp.c#L375

https://github.com/michaelrsweet/pappl/blob/97d7297ee47a21597b19791ccb660da27513db29/pappl/snmp.c#L74

**Comment by michaelrsweet** [comment]
Not really a bug but probably something that should be cleaned up so it is clear about the intent.

**Comment by michaelrsweet** [comment]
[master 9d9df5d] Workaround bogus warnings about index check happening after access (Issue #207)
