### ISSUE TITLE
1.2.1 claims to fix cups 2.2.x build problems but doesn't

### ISSUE THREAD

**Issue by janwilmans** [michaelrsweet/pappl#212]
see michaelrsweet/lprint#67 for more information

**Comment by michaelrsweet** [comment]
[master 081184e] Define more IPP operations that are missing from CUPS 2.2.x and earlier (Issue #212)

[v1.2.x ebedbbc] Define more IPP operations that are missing from CUPS 2.2.x and earlier (Issue #212)
