### ISSUE TITLE
Windows does not recognize custom page sizes

### ISSUE THREAD

**Issue by PetePriority** [michaelrsweet/pappl#215]
**Describe the bug**
I realize this might be a bug that was introduced by an update to Windows, but I'm hoping someone can point me into the right direction to resolve the following issue:

I'm using pappl together with pappl-retrofit to make an embedded printer available as an IPPEverywhere printer. The printer is not a standard desktop printer but prints on a tray onto which different material can be attached. The tray has a custom size (about 280x300mm). I originally specified this size in its PPD which I loaded with the pappl-retrofit printer application.

This worked perfectly fine until I recently tested the printer installation on an up-to-date Windows machine. Instead of showing me the available size of 280x300mm, the only paper sizes I can select are now A4 or letter. I highly suspect this is caused by a recent Windows update, since it used to work 1-2 months before.

I've tried to find a PWG size that is close to our tray size, e.g. na_11x12_11x12in, na_edp_11x14in, na_10x11_10x11in, na_10x13_10x13in, na_10x14_10x14in, na_eur-edp_12x14in, but these are ignored, too. Other page sizes, like tabloid/na_ledger_11x17in however work, but they are too large for my application.

I'm using pappl on version v1.2.1 but the problem still persists on the master branch. 

**To Reproduce**
1. Create a printer with a custom page size or any of the page sizes mentioned above.
2. Add the printer in an up-to-date Windows (10/11) 

**Expected behavior**
1. The page sizes specified in the PPD are selectable

**Actual behavior**
1. Only A4/Letter is shown as available paper sizes. If there is a recognized paper size, like tabloid, in the PPD, then only the recognized sizes are shown.

**Logs**
[log-driver-setup.txt](https://github.com/michaelrsweet/pappl/files/9228880/log-driver-setup.txt)
[log-win-installation.txt](https://github.com/michaelrsweet/pappl/files/9228881/log-win-installation.txt)
[ppd-excerpt.txt](https://github.com/michaelrsweet/pappl/files/9228882/ppd-excerpt.txt)

**Screenshots**
![Screenshot_20220731_122227](https://user-images.githubusercontent.com/8421182/182022715-c74e2e70-09f5-4ca9-a76b-ecb628efe2ef.png)
![Screenshot_20220731_122252](https://user-images.githubusercontent.com/8421182/182022716-7914afab-be08-401d-acbc-c205c8814af2.png)
![Screenshot_20220731_122316](https://user-images.githubusercontent.com/8421182/182022717-76782a85-dde6-4544-b8f7-23983a35c1d3.png)

**Comment by PetePriority** [comment]
I can reproduce this on
* Windows 10 Pro, 21H2, 19044.1766
* Windows 11 Enterprise Evaluation, 21H2, 22000.795

I was just browsing the Feedback Hub and found an [issue](https://aka.ms/AAhkbml) mentioning Update KB5015807 causing (unrelated) problems.

I can confirm that uninstalling this update fixes my problem.

**Comment by michaelrsweet** [comment]
This may be fixed starting in Windows 11 build 25124, need to test.

**Comment by PetePriority** [comment]
I can confirm this is fixed in
```
Edition	Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎09/‎10/‎2022
OS build	25217.1000
Experience	Windows Feature Experience Pack 1000.25217.1000.0
```
Thank you!

**Comment by michaelrsweet** [comment]
Awesome, thanks for testing and confirming!
