### ISSUE TITLE
Bad defaults for statedir and sockdir in Linux

### ISSUE THREAD

**Issue by abdelq** [michaelrsweet/pappl#235]
**Describe the bug**
By running `./configure` on Linux with no other specified options, one would expect `PAPPL_STATEDIR` to be `/var` and `PAPPL_SOCKDIR` to be `/var/run`, as `/usr/local/var` is a macOS thing.

**Comment by michaelrsweet** [comment]
Per FHS, they actually define locally-installed stuff under /usr/local, including /usr/local/var. And macOS wants /private/var, *not* /usr/local/var (although the latter does work since /usr/local is writable by default).

**Comment by abdelq** [comment]
[Per FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html):
<p>The following directories, or symbolic links to directories,
must be in <code class="filename">/usr/local</code></p><div class="informaltable">

Directory | Description
-- | --
bin | Local binaries
etc | Host-specific system configuration for local binaries
games | Local game binaries
include | Local C header files
lib | Local libraries
man | Local online manuals
sbin | Local system binaries
share | Local architecture-independent hierarchy
src | Local source code

</div><p>No other directories, except those listed below, may be in
<code class="filename">/usr/local</code> after first installing a FHS-compliant
system.</p>

**Comment by michaelrsweet** [comment]
So glad they've made up their minds about it, and we should all be using /run for state... 🙄 But it means overriding everything in autoconf to do it... :(
