### ISSUE TITLE
In testpappl printer properties seem not to get initialized at all

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#239]
**Describe the bug**
Printer defaults in web interface look like this:
![Screenshot from 2022-12-06 20-05-00](https://user-images.githubusercontent.com/1244825/206044263-27ce392c-b8a7-464d-88e5-7b6a3cf08821.png)
Media in the web interface looks like this:
![Screenshot from 2022-12-06 20-07-38](https://user-images.githubusercontent.com/1244825/206044409-d76cad90-ae9d-4dae-b24b-5fe6dfc25718.png)
You see that nothing is filled in and no default selection set.

It seems that no initialization of the printer driver properties data structure has taken place. Most probably it is all-zero from its initializing `calloc()`.

**To Reproduce**
1. Get GIT snapshot of PAPPL (I had commit 5a4e54098 as the last one)
2. `./configure; make; make install`
3. `cd testsuite; ./testpappl`
4. On web interface (`https://localhost:8000/`) select "Printer Defaults" or "Media" of the "Label Printer".

**System Information:**
 - Ubuntu 22.10 Kinetic Kudu

**Comment by michaelrsweet** [comment]
Hmm, probably a bug in the test suite driver, investigating.

**Comment by michaelrsweet** [comment]
[master 0366779] Fix test suite label printer drivers - default media not set (Issue #239)
