### ISSUE TITLE
pappl/test.html: For what? How did it get generated?

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#251]
The file `pappl/test.html` looks somewhat mysterious:

- The file looks machine-generated, due to its complexity, it does not contain any comments on how it could have been generated.
- There is no mention of the file name `test.html` in any of the other files in the package. No handling in the Makefiles, no access to the files in any of the `*.c` files, no mention in any of the documentation files.
- `make install` does not install `test.html`.

For me it looks like that it got accidentally committed into the GIT repository, as it does not seem to have any use in the package.

Also, for packaging PAPPL in distributions, the origin of any machine-readable file must be known. The machine-generated file can be included for convenience and to avoid the need of less common generation tools in the distro which wants to include PAPPL, but it must be full documented how the file is derived from human-generated files completely with free software.

Could the generation and use of this file be documented or the file removed?

**Comment by michaelrsweet** [comment]
Till, the file was hand-written by myself and is exclusively for testing the stylesheet, which *is* embedded as part of the library. Basically, it allows me to prototype CSS changes or specific HTML that later gets used in the `*-webif.c` files.

Really, I could add a comment to the top of the file but I'm NOT removing it!

**Comment by tillkamppeter** [comment]
Now it is all OK for me, you do not need to remove it as this way it is a legitimate part in a free software package, but it would be great if you add a comment at the top of the file, to not let other distro packagers run into the same doubt.
