### ISSUE TITLE
lprint submit of a 1-bit depth PNG is printed as all black

### ISSUE THREAD

**Issue by ribbons** [michaelrsweet/pappl#267]
I have a DYMO LabelWriter 450 and giving `lprint submit` RGB or grayscale PNGs works great, thank you!

However, giving `lprint submit` a monochrome (e.g. 1-bit depth) PNG causes it to print as if the submitted image was entirely black.  Not an issue as I can just generate grayscale or RGB PNGs instead but this did cause me a bit of head-scratching so could be worth adding to the documentation if this behaviour is 'by design' (or a hassle to fix).

Example images ~~(which hopefully GitHub hasn't been 'helpful' and re-compressed :smile:)~~ Edit: hooray, seem to have made it through unscathed.

RGB:
![RGB](https://user-images.githubusercontent.com/961548/225134944-8408e6d1-6a2c-4b9e-bf35-ee7ade94acd3.png)

1-bit:
![1-bit](https://user-images.githubusercontent.com/961548/225134965-773fb71e-ac93-4ca7-a2de-4fae3a890ece.png)

**Comment by michaelrsweet** [comment]
[master 459a417] Fix printing of grayscale PNG files (Issue #267)

[v1.3.x e762301] Fix printing of grayscale PNG files (Issue #267)
