### ISSUE TITLE
Increase the PAPPL_MAX_TYPE limit

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#268]
Michael:

This is a PPD file for a Canon imagePRESS printer, which has 78 media types and 73 vendor properties. 
When the PPD is used/selected on the legacy-printer-app, only 32 media types and 32 vendor properties are showed on the Web UI.
So, is it possible to extend the PAPPL_MAX_TYPE &  PAPPL_MAX_VENDOR ?

[CNRCUPSIPRV700ZK.ppd.txt](https://github.com/michaelrsweet/pappl/files/10999624/CNRCUPSIPRV700ZK.ppd.txt)

**Comment by michaelrsweet** [comment]
@szlt5 So there are a few issues here:

- For the "vendor properties" (options), with the exception of CNTonerSaving and CNColorToUseWithBlack they all map to existing (standard) IPP options and reflect the insanity of how finishing processes are specified differently in PPDs, even for printers from the same vendor.
- For the media types, the reason there are so many is that you have numbered versions to allow for site configuration (e.g. PlainPaper1, PlainPaper2, PlainPaper3, and PlainPaperL...) - this is insane and isn't something that is supported by IPP anyways.

WRT your request to increase the limits in PAPPL 1.x, that is not possible since it would break binary compatibility. I will look at increasing the limits in PAPPL 2.0, at least for media-type values (`PAPPL_MAX_TYPE`), but you need to map vendor names to standard IPP names wherever possible. I am less inclined to increase the `PAPPL_MAX_VENDOR` limit because few (if any) IPP client implementations support non-standard IPP attributes (options) and it is up to the printer application to properly map vendor options to their IPP counterparts. Allowing a large number of vendor attributes only encourages sloppy code that won't work well in practice.

**Comment by michaelrsweet** [comment]
[master 4005a96] Increase PAPPL_MAX_TYPE to 128 (Issue #268)

**Comment by sthibaul** [comment]
Hello,

> Allowing a large number of vendor attributes only encourages sloppy code that won't work well in practice.

We are currently looking at braille embossing, and there are a *lot* of options that don't match usual printing options at all, since they are all about braille rendering (translation table, dot distance, number of dots, braille page numbering, edge detection tuning for image printing, ...

Could this thus be reconsidered?

**Comment by sthibaul** [comment]
Just to provide the current list:

```
SendFF/Send FormFeed: Boolean
SendFF: False

SendSUB/Send Sub (^Z): Boolean
SendSUB: True

LibLouis/Braille transcription: PickOne
LibLouis2/Additional Braille transcription (2): PickOne
LibLouis3/Additional Braille transcription (3): PickOne
LibLouis4/Additional Braille transcription (4): PickOne
LibLouis: Locale
LibLouis2: Locale
LibLouis3: Locale
LibLouis4: Locale

TextDotDistance/Text dot distance: PickOne
TextDotDistance: 250

TextDots/Text dots: PickOne
TextDots: 6

LineSpacing/Line spacing: PickOne
LineSpacing: 500

TopMargin/Top margin: PickOne
TopMargin: 2

BottomMargin/Bottom margin: PickOne
BottomMargin: 2

LeftMargin/Left margin: PickOne
LeftMargin: 2

RightMargin/Right margin: PickOne
RightMargin: 2

BraillePageNumber/Braille Page Number: PickOne
BraillePageNumber: BottomMargin

PrintPageNumber/Print Page Number: PickOne
PrintPageNumber: TopMargin

PageSeparator/Print Page Separator: PickOne
PageSeparator: True

PageSeparatorNumber/Print Page Number in Separator: PickOne
PageSeparatorNumber: True

ContinuePages/Prefix Print Page Number with Braille Page Number: PickOne
ContinuePages: False

GraphicDotDistance/Graphic dot distance: PickOne
GraphicDotDistance: 200

Edge/Edge detection: PickOne
Edge: Canny

Negate/Negate: Boolean
Negate: False

EdgeFactor/EdgeFactor: PickOne
EdgeFactor: 1

CannyRadius/CannyRadius: PickOne
CannyRadius: 0

CannySigma/CannySigma: PickOne
CannySigma: 1

CannyLower/CannyLower: PickOne
CannyLower: 10

CannyUpper/CannyUpper: PickOne
CannyUpper: 30
```

That's a bit less than 32 for now, but we'd probably want to add more in the future.

**Comment by michaelrsweet** [comment]
@sthibaul IPP is *intent* based, not *process* based. Thus, a lot of PPD options don't map directly to IPP - sometimes it means you generalize, sometimes it means that an IPP intent gets mapped to one or more PPD options.

To your specific list:

> SendFF/Send FormFeed: Boolean

This might be a valid "finishings" value, or it might be a configuration setting for a specific printer and not something you specify per-job?

> SendSUB/Send Sub (^Z): Boolean

I'm assuming this is a configuration setting and not something that is set per-job.

> LibLouis/Braille transcription: PickOne
> LibLouis2/Additional Braille transcription (2): PickOne
> LibLouis3/Additional Braille transcription (3): PickOne
> LibLouis4/Additional Braille transcription (4): PickOne

Ordinarily this would be the document-natural-language attribute, which doesn't get used a lot. But for this you can provide a single "1setOf" (array) attribute that supports multiple values.

> TextDotDistance/Text dot distance: PickOne
>
> TextDots/Text dots: PickOne
>
> LineSpacing/Line spacing: PickOne

These might map directly, although I would use a prefix ("braille-" or something similar).

> TopMargin/Top margin: PickOne
>
> BottomMargin/Bottom margin: PickOne
>
> LeftMargin/Left margin: PickOne
>
> RightMargin/Right margin: PickOne

This all map directly from the media-col.xxx-margin values.

> BraillePageNumber/Braille Page Number: PickOne
>
> PrintPageNumber/Print Page Number: PickOne
>
> PageSeparator/Print Page Separator: PickOne
>
> PageSeparatorNumber/Print Page Number in Separator: PickOne
>
> ContinuePages/Prefix Print Page Number with Braille Page Number: PickOne
>
> GraphicDotDistance/Graphic dot distance: PickOne
>
> Edge/Edge detection: PickOne
>
> Negate/Negate: Boolean
>
> EdgeFactor/EdgeFactor: PickOne
>
> CannyRadius/CannyRadius: PickOne
>
> CannySigma/CannySigma: PickOne
>
> CannyLower/CannyLower: PickOne
>
> CannyUpper/CannyUpper: PickOne

Again, these can map directly or you can use one or more collections to group related attributes.

Ultimately, I see at most 19 custom options that need to be mapped.

**Comment by sthibaul** [comment]
> > SendFF/Send FormFeed: Boolean
> 
> This might be a valid "finishings" value, or it might be a configuration setting for a specific printer and not something you specify per-job?
> 
> > SendSUB/Send Sub (^Z): Boolean
> 
> I'm assuming this is a configuration setting and not something that is set per-job.

They are for a specific printer indeed: depending on the embosser brand you would need it or not. Unless we have a driver which knows that, giving this configuration option allows the user to configure the generic embossing support for their embosser. But then that's still expressed in `struct pappl_pr_driver_data_s`'s `vendor`?

> > LibLouis/Braille transcription: PickOne
> > LibLouis2/Additional Braille transcription (2): PickOne
> > LibLouis3/Additional Braille transcription (3): PickOne
> > LibLouis4/Additional Braille transcription (4): PickOne
> 
> Ordinarily this would be the document-natural-language attribute, which doesn't get used a lot.

No, it's not just a question of language. You may want to emboss using a grade1 table, or grade2, or grade0, use a user-specific table, ...

> But for this you can provide a single "1setOf" (array) attribute that supports multiple values.

Ok.

> > TextDotDistance/Text dot distance: PickOne
> > TextDots/Text dots: PickOne
> > LineSpacing/Line spacing: PickOne
> 
> These might map directly, although I would use a prefix ("braille-" or something similar).

What do you mean by "map directly"?

> > TopMargin/Top margin: PickOne
> > BottomMargin/Bottom margin: PickOne
> > LeftMargin/Left margin: PickOne
> > RightMargin/Right margin: PickOne
> 
> This all map directly from the media-col.xxx-margin values.

No, they are measured in number of characters, not millimeters.

> > BraillePageNumber/Braille Page Number: PickOne
> > PrintPageNumber/Print Page Number: PickOne
> > PageSeparator/Print Page Separator: PickOne
> > PageSeparatorNumber/Print Page Number in Separator: PickOne
> > ContinuePages/Prefix Print Page Number with Braille Page Number: PickOne
> > GraphicDotDistance/Graphic dot distance: PickOne
> > Edge/Edge detection: PickOne
> > Negate/Negate: Boolean
> > EdgeFactor/EdgeFactor: PickOne
> > CannyRadius/CannyRadius: PickOne
> > CannySigma/CannySigma: PickOne
> > CannyLower/CannyLower: PickOne
> > CannyUpper/CannyUpper: PickOne
> 
> Again, these can map directly or you can use one or more collections to group related attributes.
> 
> Ultimately, I see at most 19 custom options that need to be mapped.

That's already a lot, and much more to come (the whole set of braille rendering options in liblouisutdml is ~60 items).

**Comment by michaelrsweet** [comment]
@sthibaul 

> What do you mean by "map directly"?

I mean one named PPD option to one named IPP attribute. Often times you can combine multiple PPD options into a single IPP attribute, either as a collection (with member attributes providing the individual values) or mapping one IPP attribute/value to one or more PPD options/choices.

> No, they are measured in number of characters, not millimeters.

It doesn't matter whether you use characters, points (what used to be used for the old CUPS page-xxx attributes that were obsoleted almost a decade ago), or hundredths of millimeters (the units used for the IPP media-col collection attribute). Fundamentally these specify the margins for printed content on the media, and that functionality is already supported by the IPP media-col attribute.  PAPPL will not be providing/supporting alternatives.

> That's already a lot, and much more to come (the whole set of braille rendering options in liblouisutdml is ~60 items).

OK, so let's get real here. End users, particularly those that need to use a screen reader to manipulate the printing options, are NOT going to want to deal with a huge number of options they have to tweak for every print job. Moreover, there are precisely ZERO print clients that are able to deal with vendor-specific options at this time, and there is very little chance of that changing anytime soon.

So please stop focusing on exposing every knob as an IPP attribute.

The way to deal with large number of options like this (and I am telling the Gutenprint developers the same thing) is to:

1. Provide web UI to create named presets that are exposed via a single vendor attribute. *If* vendor attributes are ever supported by common print clients, *that* is the easiest to support, and will thus be the most likely to be supported. This method will also work well with future support of the "job-presets-supported" attribute in PAPPL, and *that* attribute is already supported by existing print clients.
2. If you insist on providing attributes for every option, combine/group PPD options into IPP collection attributes, which can contain an arbitrary number of member attributes. I don't recommend putting everything into a single attribute, but for the options you have shown thus far you can probably do two collections for dot and page settings, with a handful of other attributes for the settings that don't fit into either grouping.

But to make things crystal clear: no, I will not be increasing the `PAPPL_MAX_VENDOR` value and will not reconsider that decision.

**Comment by sthibaul** [comment]
> @sthibaul
> 
> > What do you mean by "map directly"?
> 
> I mean one named PPD option to one named IPP attribute.

Ok, but do you mean a vendor attribute or something else?

> > No, they are measured in number of characters, not millimeters.
> 
> It doesn't matter whether you use characters, points, or hundredths of millimeters

The thing is: we need both. When embossing images, you specify the margin in number of millimeters (including the hardware margin), so it's really like media-col.xxx-margin. But when embossing text, you specify the margin in number of characters *in addition to the hardware margin*. They are really not the same at all.

> > That's already a lot, and much more to come (the whole set of braille rendering options in liblouisutdml is ~60 items).
> 
> OK, so let's get real here. End users, particularly those that need to use a screen reader to manipulate the printing options, are NOT going to want to deal with a huge number of options they have to tweak for every print job.

Yes, they will. The fact that they use a screen reader does not matter (why would it matter??!).

Embossing a document is a very involved thing, one takes a lot of care when doing this. The translation, the page numbering, etc. are really important things. It's really *far* from "I'll just print that pdf over to paper" that sighted people can say.

> Moreover, there are precisely ZERO print clients that are able to deal with vendor-specific options at this time, and there is very little chance of that changing anytime soon.

That is not really a concern, since people will either use the command-line directly, or use a dedicated client that knows these options, or configure their embosser in the web interface.

> So please stop focusing on exposing every knob as an IPP attribute.

People do *want* to be able to tune these knobs.

>     1. Provide web UI to create named presets that are exposed via a single vendor attribute.

I don't remember embossing tools providing presets.

> This method will also work well with future support of the "job-presets-supported" attribute in PAPPL, and _that_ attribute is already supported by existing print clients.

Ok, I'll check if that can make sense.

>     2. If you insist on providing attributes for every option, combine/group PPD options into IPP collection attributes, which can contain an arbitrary number of member attributes.

Ok.
