### ISSUE TITLE
DYMO USB serial number issue

### ISSUE THREAD

**Issue by mikestamat** [michaelrsweet/pappl#271]
I have three Dymo Labelwriters connected to a Raspberry Pi 3. Because Dymo does not report the printer serial number in the Device ID, I compiled OpenPrinting CUPS from source using the instructions @michaelrsweet described in this known issue: (https://github.com/OpenPrinting/cups/issues/170) ... and also discussed here: (https://ubuntuforums.org/showthread.php?t=2441092)

The install was successful and lpinfo reported the unique device URIs for each printer. However, when attempting to add a printer via the CUPS web interface, the page would error out and checking the logs reported: 
`W [09/Apr/2023:16:14:41 -0400] Printer drivers are deprecated and will stop working in a future version of CUPS. See https://github.com/OpenPrinting/cups/issues/103`

It appears the fix action is migrating away from OpenPrinting CUPS to lprint, but unfortunately the previous issue has surfaced again.
`pi@rpi3:~ $ sudo snap run lprint server -o server-name=rpi3 -o server-port=632 -o auth-service=cups 
DYMO LabelWriter 450 (USB) (usb://DYMO/LabelWriter%20450?serial=01010112345600;MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;) -> dymo_lw-450
DYMO LabelWriter 450 (USB) (usb://DYMO/LabelWriter%20450?serial=01010112345600;MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;) -> dymo_lw-450
E [2023-04-09T20:44:42.257Z] Printer 'DYMO LabelWriter 450' already exists.
DYMO LabelWriter 450 Turbo (USB) (usb://DYMO/LabelWriter%20450%20Turbo?serial=17082908152669;MFG:DYMO;CMD: ;MDL:LabelWriter 450 Turbo;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450 Turbo;SERN:17082908152669;) -> dymo_lw-450-turbo
E [2023-04-09T20:44:42.264Z] Unable to register 'LPrint._ipps-system._tcp': Local name collision
E [2023-04-09T20:44:43.328Z] Unable to register 'LPrint._ipps-system._tcp': Local name collision`

Requesting a fix for lprint to handle this known Dymo bug.

**Comment by michaelrsweet** [comment]
Changed the title and moved to PAPPL, which is responsible for USB device support. There *is* workaround code in PAPPL but it doesn't kick in if the printer reports a serial number in the 1284 device ID...

DYMO is hardly the only offender in this behavior, but it is frustrating...

**Comment by mikestamat** [comment]
Thanks for the quick reply! Standing by to test in v1.4

**Comment by michaelrsweet** [comment]
[master 92223bc] Use the USB device serial number instead of the 1284 serial number value (Issue #271)

[v1.3.x f1e45ef] Use the USB device serial number instead of the 1284 serial number value (Issue #271)

Need to test but this mirrors the CUPS USB backend.

**Comment by mikestamat** [comment]
Sorry for the n00b question, but how can I go about testing this? Since it appears you merged to master for this fix, I did git clone https://github.com/michaelrsweet/pappl and attempted to compile from source. I guess I need the cups developer package? Assuming I get pappl installed then do I need to compile lprint from source with configure referencing my pappl files?
