### ISSUE TITLE
"Paused" state not persisted

### ISSUE THREAD

**Issue by andreaskem** [michaelrsweet/pappl#286]
**Describe the bug**
This bug was encountered using `lprint` but I was sent here to report the actual issue:
When pausing a printer (or its associated queue), its state is not persisted across service restarts.

**To Reproduce**
```
$ lprint pause -d lpne3
$ lprint status -d lpne3
Running, stopped since Thu, 31 Aug 2023 05:47:00 GMTpaused.
$ sudo systemctl restart lprint
$ lprint status -d lpne3
Running, idle since Thu, 31 Aug 2023 05:48:29 GMT.
```

**Expected behavior**
A paused printer should not be restarted by a reboot or service restart. For example, a printer might suddenly start printing many jobs after a system reboot.

**System Information:**
 - OS: Linux (Arch Linux)
 - pappl 1.3.2
 - cups 2.4.6
 - lprint 1.2.0

**Additional context**
Pausing a printer does not seem to have an effect on `/etc/lprint.conf`, where I assume its state should be persisted.

**Comment by michaelrsweet** [comment]
[master caca78c] When multiple queues are supported, preserve the paused state of each printer (Issue #286)
