### ISSUE TITLE
Deadlock happens when listing devices

### ISSUE THREAD

**Issue by tangyanli** [michaelrsweet/pappl#299]
Hi, Michael:

**Describe the bug**
This is a rare case. And I discovered it by accident.
When the avahi-daemon is stopped, deadlock happens when listing devices.

**To Reproduce**
1. Stop avahi-daemon. (I am investigation how the avahi-socket activate the avahi-daemon, so I stop it firstly.)
2. Run the command "legacy-printer-app devices" for the first time, only the SNMP devices are listed.
3. Run the command "legacy-printer-app devices" for the second time, deadlock happens.

**System Information:**
 - OS: Ubuntu22.10
 - Browser: firefox
 - Version: pappl 1.4.x

**Additional context**
I debug the code, when the avahi-daemon is stopped, the function `pappl_dnssd_list()` exited without invoking the `_papplDNSSDUnlock'.
```
_papplDNSSDLock();            ★ get lock

#  ifdef HAVE_MDNSRESPONDER
  pdl_ref = _papplDNSSDInit(NULL);

  _PAPPL_DEBUG("pappl_dnssd_find: pdl_ref=%p (before)\n", pdl_ref);

  if ((error = DNSServiceBrowse(&pdl_ref, kDNSServiceFlagsShareConnection, 0, "_pdl-datastream._tcp", NULL, (DNSServiceBrowseReply)pappl_dnssd_browse_cb, devices)) != kDNSServiceErr_NoError)
  {
    _papplDeviceError(err_cb, err_data, "Unable to create service browser: %s (%d).", _papplDNSSDStrError(error), error);
    cupsArrayDelete(devices);
    return (ret);
  }

  _PAPPL_DEBUG("pappl_dnssd_find: pdl_ref=%p (after)\n", pdl_ref);

#  else
  if ((pdl_ref = avahi_service_browser_new(_papplDNSSDInit(NULL), AVAHI_IF_UNSPEC, AVAHI_PROTO_UNSPEC, "_pdl-datastream._tcp", NULL, 0, pappl_dnssd_browse_cb, devices)) == NULL)
  {
    _papplDeviceError(err_cb, err_data, "Unable to create service browser.");
    cupsArrayDelete(devices);
    return (ret);           ★ exit directly
  }
#  endif // HAVE_MDNSRESPONDER

  _papplDNSSDUnlock();     ☆ Unlock doesn't run
```

**Comment by michaelrsweet** [comment]
[v1.4.x 7188d72] Add missing unlock to DNS-SD code (Issue #299)
