### ISSUE TITLE
The attributes "output-bin" and "sides" cannot be set by IPP operation "IPP_OP_SET_PRINTER_ATTRIBUTES"

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#305]
**Is your feature request related to a problem? Please describe.**
The attributes "output-bin" and "sides" can be set on the web "localhost:8000/foo/printing" but cannot be set by   the IPP operation "IPP_OP_SET_PRINTER_ATTRIBUTES". The two attributes are skipped in the function `_papplPrinterSetAttributes()`

**Describe the solution you'd like**
Is it possible to accept the two attributes in the function `_papplPrinterSetAttributes()`?

**Comment by michaelrsweet** [comment]
Yes, for output-bin-default and sides-default. Looks like they are the only missing attributes...

**Comment by michaelrsweet** [comment]
[master 1dbeea3] Fix output-bin-default and sides-default support with Set-Printer-Attributes (Issue #305)

[v1.4.x 2fa7ed1] Fix output-bin-default and sides-default support with Set-Printer-Attributes (Issue #305)

**Comment by szlt5** [comment]
Checked, the output-bin-default and sides-default can be set now. Thanks!
