### ISSUE TITLE
"printer-settable-attributes" and _papplPrinterSetAttributes are inconsistent

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#311]
**Is your feature request related to a problem? Please describe.**
I found the "printer-settable-attributes" acquired by IPP is inconsistent with the acceptable attributes in the function `_papplPrinterSetAttributes()`.

Would it be more appropriate to change them consistent?

**Additional Information**
The “printer-settable-attributes" is acquired by following command:
```
ipptool -tv ipp://localhost:8000/ipp/print/foo get-printer-attributes-3.0.test
```
![None](https://github.com/michaelrsweet/pappl/assets/117269245/c52a53e1-1bdc-4e37-843d-71262c408905)

**Comment by michaelrsweet** [comment]
"document-format-default" shouldn't be listed.

"output-bin-default", "printer-contact-col", and "sides-default" should be listed.

**Comment by szlt5** [comment]
Now, only the master branch can set "copy-default", it is helpful to accept the "copies-default" in the function _papplPrinterSetAttributes() for the branch 1.4.x.

**Comment by michaelrsweet** [comment]
@szlt5 The `pappl_pr_driver_data_t` structure in 1.x does not support copies - 1.x assumed that the printers supported by the various drivers would not be able to usefully support copy generation and didn't expose it. So "copies-default" needs to be a 2.0 and later feature...

**Comment by michaelrsweet** [comment]
[master 2d25c1d] Update the printer-settable-attributes-supported values (Issue #311)

[v1.4.x 1e28cdf] Update the printer-settable-attributes-supported values (Issue #311)
