### ISSUE TITLE
The option of "-n COPIES" doesn't work

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#312]
**Describe the bug**
The option of "-n COPIES" doesn't work.

**To Reproduce**
1. Run below command `legacy-printer-app --help`, below usage shows
```
...
Options:
-n COPIES    Specify number of copies (submit)
```
2. Submit a file for printing with copies set as 2 
```
legacy-printer-app submit -n 2 testpage.ps
```
3. Only 1 copy is printed out.

**Expected behavior**
Two copies should be printed out.

**Additional context**
1. If use below command to submit, two copies are printed out.
```
legacy-printer-app submit -o copies=2 testpage.ps
```
2. In function `papplMainloop()`, the option `'-n'` is converted as `"num-copies"`. Should the option `'-n'` be converted as `"copies"`?

**Comment by michaelrsweet** [comment]
Yes, it needs to just be "copies". I don't know why I wrote it as "num-copies"...

**Comment by michaelrsweet** [comment]
[master 90b6496] Fix -n option to set number of copies (Issue #312)

[v1.4.x 88a67cf] Fix -n option to set number of copies (Issue #312)
