### ISSUE TITLE
Query about the "finishing"

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#317]
**Is your feature request related to a problem? Please describe.**
I am trying to map vendor finishing names to standard IPP names, but it's hard to do.

The pappl supports below finishings 
```
enum pappl_finishings_e			// IPP "finishings" bit values
{
  PAPPL_FINISHINGS_NONE = 0x0000,		// 'none'
  PAPPL_FINISHINGS_PUNCH = 0x0001,		// 'punch'
  PAPPL_FINISHINGS_STAPLE = 0x0002,		// 'staple'
  PAPPL_FINISHINGS_TRIM = 0x0004		// 'trim'
};

```
I checked a hardware device, and the device returns below finishing capability. 
```
finishings-ready (1setOf enum) = staple,staple-top-left,staple-bottom-left,staple-top-right,staple-bottom-right,staple-dual-left,staple-dual-top,staple-dual-right,staple-dual-bottom,saddle-stitch,fold,fold-half,punch,punch-dual-left,punch-dual-top,punch-dual-right,punch-dual-bottom,punch-quad-left,punch-quad-top,punch-quad-right,punch-quad-bottom,none
```
Then I continued to look up the IPP protocol, found huge finishing capabilities are defined. Would pappl support more finishings in future?
```
RFC 2911		
	None (3): Perform no finishing	
	staple(4): Bind the Set(s) with one or more staples. The exact number placement, and orientation of the staples are implementation and/or site-defined.	
	punch(5): The value indicates that holes are required in the finished hardcopy output.	
	cover (6): This value is specified when it is desired to select a non-printed (or pre-printed) cover for each set.	
	bind (7): This value indicates that binding is to be applied to the Set.	
	saddle-stitch (8): Bind the Set(s) with two or more staples (wire stitiches) along the middle fold.	
	edge-stitch (9): Bind the Set(s) with two or more staples (wire stitiches) along one edge. The exact nunber and placement of the staples are implementation and or site-defined,	
	staple-top-left (20): Bind the sets with one or more staples in the top left corner.	
	staple-bottom-left(21): Bind the sets with one or more staples in the bottom left corner.	
	staple-top-right(22): Bind the sets with one or more staples in the top right corner.	
	staple-bottom-left(23): Bind the sets with one or more staples in the bottom right corner.	
	edge-stitch-left (24): Bind the sets with two or more staples along the left edge. The exact and placement of the staples are implementation and/or site-defined.	
	edge-sitich-top (25): Bind the sets with two or more staples along the top edge.	
	edge-sitich-right (26): Bind the sets with two or more staples along the right edge.	
	edge-sitich-bottom (27): Bind the sets with two or more staples along the bottom edge.	
	staple-dual-left (28): Bind the sets with two staples (wire stitches) along the left edge assuming a portrait document.	
	staple-dual-top (29): Bind the sets with two staples (wire stitches) along the top edge assuming a portrait document.	
	staple-dual-right (30): Bind the sets with two staples (wire stitches) along the right edge assuming a portrait document.	
	staple-dual-bottom (31): Bind the sets with two staples (wire stitches) along the bottom edge assuming a portrait doucment.	
PWG 5100.1-2001 "finishings" values		
The IPP "finishings" attribute vslues extension defines the following "finishings" enum values:		
	fold (10): Fold the hardcopy output. The exact number and orientations of the folds is implementation and / or site-defined.	
	trim(11): Trim the hardcopy outout on one or more edges.	
	bale (12): bale the sets.	
	booklet-marker (13): Deliver the sets to the signature booklet marker. This value is a short cut for specifying a job that is to be folded, trimmed and then saddle-sititched.	
	jog-offset (14): Shift each set from the previous one by small amount which is device dependent.	
	bind-left (50): Bind the set along the left edge; the type of the binding is implementation and / or site-defined.	
	bind-top (51): Bind the sets along the top edge; the type of the binding is implementation and / or site-defined.	
	bind-right (52):  Bind the set(s) along the right edge; the type of the binding implementation and / or is site-defined.	
	bind-bottom (53): Bind the set(s) along the bottom edge; the type of the binding is implementation and / or site-defined.	
PWG 5100.1-2014 "finishings" values		
The IPP Finishings 2.0 specification defines the following "finishings" enum values:		
	coat(15): Apply a protective liquid or powdered coating to each sheet in an implementation and/or site-defined manner.	
	laminate(16): Apply a protective (solid) material to each sheet in an implementation and / or site-defined manner.	
	staple-triple-left (32): Bind the sets with three staples (wire sitiches) along the left edge assuming a portrait document.	
	staple-triple-top (33): Bind the sets with three staples (wire stitches) along the top edge assuming a portrait document.	
	staple-tripe-right (34): Bind the sets with three staples (wire sitches) along the right edge assuming a portrait document.	
	staple-triple-bottom (35): Bind the sets with three staples (wire stitches) along the top edge assuming a portrait document.	
	punch-top-left (70): Punch a single hole in the top left of the hardcopy output.	
	punch-bottom-left (71): Punch a single hole in the bottom left of the hardcopy output.	
	punch-top-right (72): Punch a single hole in the top right of the hardcopy output.	
	punch-bottom-right (73): Punch a single hole in the bottom right of the hardcopy output.	
	punch-dual-left (74): Punch two holes on the left side of the hardcopy output.	
	punch-dual-top (75): Punch two holes at the top of the hardcopy output.	
	punch-dual-right (76): Punch two holes on the right side of the hardcopy output.	
	punch-dual-bottom (77): Punch two holes at the bottom of the hardcopy output.	
	punch-triple-left (78): Punch three holes on the left side of the hardcopy output.	
	punch-triple-top (79): Punch three holes at the top at the hardcopy output.	
	punch-triple-right (80): Punch three holes at the right side of the hardcopy outout.	
	punch-triple-bottom (81): Punch three holes at the bottom of the hardcopy output.	
	punch-quad-left (82): Punch four holes on the left side of the hardcopy output.	
	punch-quad-top (83): Punch four holes at the top of the hardcopy output.	
	punch-quad-right (84): Punch four holes on the right side of the hardcopy output.	
	punch-quad-bottom (85): Punch four holes at the bottom of the hardcopy output.	
	fold-accordion (90): Accordion-fold the hardcopy output vertically into four section.	
	fold-double-gate (91): Fold the top ad bottom quarters of the hardcopy outout towards the midline, then fold in half vertically.	
	fold-gate (92): Fold the top and bottom quarters of the hardcopy output towards the midline.	
	fold-half (93): Fold the hardcopy output in half vertically.	
	fold-half-z (94): Fold the hardcopy output in half horizontally, then Z-fold the paper vertically into three sections.	
	fold-left-gate (95): Fold the top quarter of the hardcopy output towards the midline.	
	fold-letter: Fold the hardcopy outout into three sections vertically; something also known as C fold.	
	fold-parallel(97): Fold the hardcopy output in half vertically two times, yielding four sections.	
	fold-poster (98): Fold the hardcopy output in half horizontally and vertically; sometimes also called a cross fold.	
	fold-right-gate (99): Fold the bottom quarter of the hardcopy output towards the midline.	
	fold-z: Fold the hardcopy output vertically into three sections, forming a Z.	
PWG 5100.1-2017 "finishings" values		
The IPP Finishings 2.0 specification defines the following "finishings" enum values:		
	fold-engineering-z (101): Fold the hardcopy output vertically into three sections. forming a Z but leaving room for binding, punching, or stapling along the top edge.	
	punch-multiple-left (86): Drill or punch more than four holes along the reference edge.	
		For 1-4 holes, the individual explicit value ('punch-top-left', 'punch-dual-left', 'punch-triple-left' and 'punch-qual-left') should be used instead.
		The number and location of holes can be advertised by the Printer in the "finishings-col-database" and "finishing-col-ready" Printer Description attributes in the "punching" member attribute.
	punch-multiple-top(87): Drill or punch more than four holes along the reference edge.	
	punch-multiple-right (88): Drill or punch more than four holes along the reference edge.	
	punch-multiple-bottom (89): Drill or punch more than four holes along the reference edge.	
PWG 5100.13 "finishings" values		
	trim-after-pages: Trim output after each page.	
	trim-after-documents: Trim output after each document.	
	trim-after-copies: Trim output after each set.	
	trim-after-job: Trim output after job.
```

**Comment by michaelrsweet** [comment]
The list of available finishing options was kept small on purpose - I covered the most common finishing options that I've seen actually supported by PPD files and wanted to reserve additional bits only as needed.

If you can attach some representative PPD files showing the kinds of finishing options you would like supported, I can extend the list for PAPPL 2.0.

**Comment by szlt5** [comment]
@michaelrsweet 
I have posted the PPD file in the https://github.com/michaelrsweet/pappl/issues/268

**Comment by szlt5** [comment]
I will try to sort out the maps between the vendor attributes and the IPP finishings later.

**Comment by michaelrsweet** [comment]
So looking at the PPD file from that bug I see the following mappings:

Installable Options
------------------

- `CNFinisher`
- `CNFolder`
- `CNInsertUnit`
- `CNProPuncher`
- `CNPuncher`
- `CNSrcOption`
- `CNTrimmer`


Standard Options
-----------------

- `Collate`: multiple-document-handling
- `Duplex`: sides
- `InputSlot`: media-col.media-source
- `MediaType`: media-col.media-type
- `OutputBin`: output-bin
- `PageSize`/`PageRegion`: media/media-col.media-size/media-col.media-size-name
- `Resolution`: printer-resolution


Finishing Options
-----------------

- `BindEdge`: determines left/top location of other finishing options
- `Booklet`: finishings='13' (booklet-maker) for `Booklet=Right` (but according to
  the PPD spec v4.3, this option should be a boolean, so more generally
  `Booklet=True`)
- `CNAccordionZfolding`: finishings='100' (fold-z) for CNAccordionZfolding=True
- `CNAccordionZfoldSetting`: map orientation-requested='3' (portrait) or '6'
  (reverse-portrait) to `CNAccordionZfoldSetting=pattern1`, map others to
  `CNAccordionZfoldSetting=pattern2`
- `CNAdjustTrim`: No mapping and honestly no idea what it does?
- `CNCfolding`: finishings='91' (fold-double-gate)
- `CNCfoldSetting`: map orientation-requested='3' (portrait) or '6'
  (reverse-portrait) to `CNCfoldSetting=pattern1`, map others to
  `CNCfoldSetting=pattern2`
- `CNCrease`: no mapping (and not clear what the expectation is here)
- `CNDoubleParallelFolding`: finishings='97' (fold-parallel)
- `CNDoubleParallelFoldSetting`: map orientation-requested='3' (portrait) or '6'
  (reverse-portrait) to `CNDoubleParallelFoldSetting=pattern1`, map others to
  `CNDoubleParallelFoldSetting=pattern2`
- `CNHalfFolding`: finishings='93' (fold-half)
- `CNHalfFoldSetting`: map orientation-requested='3' (portrait) or '6'
  (reverse-portrait) to `CNHalfFoldSetting=pattern1`, map others to
  `CNHalfFoldSetting=pattern2`
- `CNInterleafMediaType`: insert-sheet.media-col.media-type
- `CNInterleafPrint`: no mapping
- `CNInterleafSheet`: insert-sheet
- `CNMultiPunch`: `CNMultiPunch=PUNU2` is finishings='74' (punch-dual-left) or
  finishings='75' (punch-dual-top), `CNMultiPunch=PUNU23` is finishings='75'
  (punch-dual-top) for `CNPunch=Top` or finishings='78' (punch-triple-left) for
  `CNPunch=Left`, `CNMultiPunch=PUNU3` is finishings='78' (punch-triple-left)
  or finishings='79' (punch-triple-top), `CNMultiPunch=PUNM` is finishings='86'
  (punch-multiple-left) for `CNPunch=Left`, finishings='87' (punch-multiple-top)
  for `CNPunch=Top`
- `CNOutputFace`: page-delivery='reverse-order-face-up' for
  `CNOutputFace=FaceUp` and page-delivery='same-order-face-down' for
  `CNOutputFace=FaceDown`
- `CNOutputPartition`: no mapping
- `CNPerforation`: no mapping (and not clear what the expection is here)
- `CNPunch`: Control edge for punch
- `CNSaddleFolding`: finishings='93' (fold-half) for orientation-requested='4'
  or orientation-requested='5'
- `CNSaddleFoldSetting`: map orientation-requested='3' (portrait) or '6'
  (reverse-portrait) to `CNSaddleFoldSetting=pattern1`, map others to
  `CNSaddleFoldSetting=pattern2`
- `CNSaddleFoldSheetsNum`: job-pages-per-set
- `CNSaddleStitch`: finishings='8' (saddle-stitch)
- `CNSetBackSheet`: cover-back
- `CNSetFrontSheet`: cover-front
- `CNTrimming`: finishings='11' (trim)
- `CNVfolding`: finishings='93' (fold-half) for orientation-requested='3' or
  orientation-requested='6'
- `CNZfolding`: finishings='100' (fold-z)
- `StapleLocation`: finishings='20' (staple-top-left) for `StapleLocation=TopLeft`,
  finishings='29' (staple-dual-top) for `StapleLocation=Top`,
  finishings='22' (staple-top-right) for `StapleLocation=TopRight`,
  finishings='28' (staple-dual-left) for `StapleLocation=Left`,
  finishings='21' (staple-bottom-left) for `StapleLocation=BottomLeft`


Production Options
-------------------

- `CNBackPaperSrc`: cover-back.media-col.media-source (sort of)
- `CNBackPrintOn`: cover-back
- `CNCopySetNumbering`: no mapping
- `CNFrontPaperSrc`: cover-front.media-col.media-source (sort of)
- `CNFrontPrintOn`: cover-front
- `CNPoster`: Probably imposition-template


Vendor (Quality/Processing) Options
------------------------------------

- `CNAdvancedSmoothing`
- `CNColorHalftone`
- `CNColorMode`
- `CNColorToUseWithBlack`
- `CNCreep`
- `CNDisplacementCorrection`
- `CNHalftone`
- `CNHyperSharpness`
- `CNJobExecMode`
- `CNLineControl`
- `CNMatchingMethod`
- `CNNumberOfColors`
- `CNObjectPrioritizeProcessing`
- `CNOptimizeImageComp`
- `CNSharpness`
- `CNShiftStartPrintPosition`:
- `CNSpecifyNumOfCopiesStack`
- `CNTimingOfAutoEjectStacker`
- `CNTonerDensity`
- `CNTonerSaving`
- `CNTonerVolumeAdjustment`
- `CNWidthAdjustment`


So this means we need the following additional finishing options:

```c
  PAPPL_FINISHINGS_BOOKLET_MAKER = 0x000008,	// 'booklet-maker'

  PAPPL_FINISHINGS_FOLD_DOUBLE_GATE = 0x000010,	// 'fold-double-gate'
  PAPPL_FINISHINGS_FOLD_HALF = 0x000020,	// 'fold-half'
  PAPPL_FINISHINGS_FOLD_LETTER = 0x000040,	// 'fold-letter'
  PAPPL_FINISHINGS_FOLD_PARALLEL = 0x000080,	// 'fold-parallel'
  PAPPL_FINISHINGS_FOLD_Z = 0x000100,		// 'fold-z'

  PAPPL_FINISHINGS_PUNCH_DUAL_LEFT = 0x000200,	// 'punch-dual-left'
  PAPPL_FINISHINGS_PUNCH_DUAL_TOP = 0x000400,	// 'punch-dual-top'
  PAPPL_FINISHINGS_PUNCH_TRIPLE_LEFT = 0x000800,// 'punch-triple-left'
  PAPPL_FINISHINGS_PUNCH_TRIPLE_TOP = 0x001000,	// 'punch-triple-top'
  PAPPL_FINISHINGS_PUNCH_MULTIPLE_LEFT = 0x002000,// 'punch-multiple-left'
  PAPPL_FINISHINGS_PUNCH_MULTIPLE_TOP = 0x004000,// 'punch-multiple-top'

  PAPPL_FINISHINGS_SADDLE_STITCH = 0x008000,	// 'saddle-stitch'

  PAPPL_FINISHINGS_STAPLE_TOP_LEFT = 0x010000,	// 'staple-top-left'
  PAPPL_FINISHINGS_STAPLE_BOTTOM_LEFT = 0x020000,// 'staple-bottom-left'
  PAPPL_FINISHINGS_STAPLE_TOP_RIGHT = 0x040000,	// 'staple-top-right'
  PAPPL_FINISHINGS_STAPLE_BOTTOM_RIGHT = 0x080000,// 'staple-bottom-right'
  PAPPL_FINISHINGS_STAPLE_DUAL_LEFT = 0x100000,	// 'staple-dual-left'
  PAPPL_FINISHINGS_STAPLE_DUAL_TOP = 0x200000,	// 'staple-dual-top'
```

**Comment by szlt5** [comment]
Thanks! @michaelrsweet , I will follow and test the new supported finishings.

**Comment by michaelrsweet** [comment]
[master 6491255] Add more finishings options (Issue #317)

**Comment by szlt5** [comment]
> Plus, you don't have more than 32 options (I count 10 from your list above).

The following attributes should also be added：
> ## Vendor (Quality/Processing) Options
> * `CNAdvancedSmoothing`
> * `CNColorHalftone`
> * `CNColorMode`
> * `CNColorToUseWithBlack`
> * `CNCreep`
> * `CNDisplacementCorrection`
> * `CNHalftone`
> * `CNHyperSharpness`
> * `CNJobExecMode`
> * `CNLineControl`
> * `CNMatchingMethod`
> * `CNNumberOfColors`
> * `CNObjectPrioritizeProcessing`
> * `CNOptimizeImageComp`
> * `CNSharpness`
> * `CNShiftStartPrintPosition`:
> * `CNSpecifyNumOfCopiesStack`
> * `CNTimingOfAutoEjectStacker`
> * `CNTonerDensity`
> * `CNTonerSaving`
> * `CNTonerVolumeAdjustment`
> * `CNWidthAdjustment`
