### ISSUE TITLE
Driverless cannot get the "printer-strings-uri" attribute

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#321]
**Describe the bug**
Driverless will generate the localization strings based on the "printer-strings-uri" attributes. 
But for the legacy-printer-app, driverless fails to get the "printer-strings-uri" attributes.

**To Reproduce**
1. In the legacy-printer-app, call the `papplSystemAddStringsData()` to add a static localization resource.
2. Run `leagcy-printer-app server`
3. Generate driverless ppd by command `lpadmin -p foo -v ipp://localhost:8000/ipp/print/foo -m driverless:ipp://localhost:8000/ipp/print/foo`
4. The ppd doesn't show localization strings.

**Additional context**
Did some investigation:

* Driverless connects to pappl and attempts to get the printer attributes: "all" & **"media-col-database"**. But pappl doesn't return the `printer-strings-uri` attributes.

* In `cfGetPrinterAttributes5()`, remove the **"media-col-database"** to make Driverless only get the printer attributes "all", pappl can return the `printer-strings-uri` attributes.

* The command `ipptool -tv ipp://localhost:8000/ipp/print/foo get-printer-attributes-3.0.test` **can show** the `printer-strings-uri`.

* But the command `ipptool -tv ipp://localhost:8000/ipp/print/foo get-printer-attributes-2.0.test`  **doesn't show** the `printer-strings-uri`.

* Connect to a hardware device, both `ipptool -tv ipp://...  get-printer-attributes-2.0.test` and `ipptool -tv ipp://...  get-printer-attributes-3.0.test` can show the `printer-strings-uri`.

* `ra = ippCreateRequestedArray()` in function `ipp_get_job_attributes()` doesn't seem to be returning the correct result... but I didn't investigate further..

**Comment by michaelrsweet** [comment]
What version of CUPS are you linking against?

**Comment by szlt5** [comment]
should be 2.4.x, I don't remember the minor version, will check and reply again in next Monday.

**Comment by szlt5** [comment]
It's my fault. I linked against the CUPS v2.4.2.
After upgrade to CUPS v2.4.6, this issue is fixed.
