### ISSUE TITLE
Printer speed not saved for TSPL 203dpi

### ISSUE THREAD

**Issue by proski** [michaelrsweet/pappl#330]
I can finally use Munbyn ITPP-941 with lprint. However, it resets to the slowest speed on system reboot. Not only is the printer painfully slow, it's much noisier at the low speed.

It turns out the speed is not saved in `/etc/lprint.conf`. I tried adding the printer with different speeds, and I don't see any relevant difference in the contents of `/etc/lprint.conf`.

I enabled debug information for the server, but I don't see any errors or warnings about configuration. I see that the speed is received by the server, but it becomes 0 after the server is restarted.

```
# journalctl -b -u lprint | grep -i speed
Jan 31 22:12:44 mbp lprint[12630]: D [2024-02-01T06:12:44.934Z] [Client 2] Create-Printer request:   print-speed-default integer 10160
Jan 31 22:12:44 mbp lprint[12630]: D [2024-02-01T06:12:44.936Z] [Client 2] printer-attributes-tag print-speed-default integer ...
Jan 31 22:15:30 mbp lprint[12630]: D [2024-02-01T06:15:30.437Z] [Client 4] Create-Printer request:   print-speed-default integer 12700
Jan 31 22:15:30 mbp lprint[12630]: D [2024-02-01T06:15:30.439Z] [Client 4] printer-attributes-tag print-speed-default integer ...
Jan 31 22:23:46 mbp lprint[12630]: D [2024-02-01T06:23:46.273Z] [Client 6] Create-Printer request:   print-speed-default integer 7620
Jan 31 22:23:46 mbp lprint[12630]: D [2024-02-01T06:23:46.274Z] [Client 6] printer-attributes-tag print-speed-default integer ...
Jan 31 22:26:38 mbp lprint[12630]: D [2024-02-01T06:26:38.370Z] [Job 1] print-speed=7620
Jan 31 22:26:38 mbp lprint[12630]: D [2024-02-01T06:26:38.370Z] [Job 1] print-speed=7620
--- the server is restarted ---
Jan 31 22:31:54 mbp lprint[13705]: D [2024-02-01T06:31:54.459Z] [Job 2] print-speed=0
Jan 31 22:31:54 mbp lprint[13705]: D [2024-02-01T06:31:54.459Z] [Job 2] print-speed=0
```

Command line to add the printer:
```
lprint add -d LabelPrinter -m tspl_203dpi -v 'usb://Munbyn%20/ITPP941?serial=9412033000184' -o print-speed=3in -o printer-darkness=90 -o printer-location=Nook
```

I'm printing a PDF file from Mozilla Firefox 122.0.
OS: Fedora 39 x86_64, all up-to-date
lprint: 1.3.0
pappl: current v1.4.x branch (bb4cc9a587890078d0f7eb5291cf6d6aac3ccbe8)
libcupsfilters: current master branch (ae55809fae7ba834bc3bb3fe90c2aa5d87ab9de1)
[lprint.conf](https://github.com/michaelrsweet/lprint/files/14121444/lprint.conf.txt)

**Comment by michaelrsweet** [comment]
Also there is no way to set the default speed with this driver, and it looks like maybe print-darkness-default isn't getting saved either. Need to do a sweep...

**Comment by proski** [comment]
`printer-darkness` is saved but incorrectly. I set it to 90, it's saved as 50. `printer-location` is not saved at all.

**Comment by michaelrsweet** [comment]
[master e422c97] Make sure to save/load all defaults (Issue #330)

[v1.4.x b670d48] Make sure to save/load all defaults (Issue #330)
