### ISSUE TITLE
Printer darkness reset from 0% to default

### ISSUE THREAD

**Issue by proski** [michaelrsweet/pappl#337]
**Describe the bug**
If the printed darkness is set to 0% in the lprint web interface, it's reset to the default value (53%) after the lprint server restarts. Observed with TSPL 203dpi driver.

**To Reproduce**
1. Go to lprint web interface
2. Set printer darkness to 0% and save settings
3. Restart lprint: `sudo systemctl restart lprint`
4. Refresh lprint web interface
5. The printer darkness is shown as 53% in the web interface.

**Expected behavior**
The printer darkness is shown as 0% in the web interface.

**System Information:**
 - OS: Fedora Workstation 39 x86_64
 - Browser: Firefox
 - Version: master branch of lprint, 1.4.x branch of pappl

**Additional context**
When any non-zero darkness is configured, it's saved in `/etc/lprint.conf` on a line starting with `printer-darkness-configured`. When the darkness is set to 0%, that line is absent. It appears that zero darkness is treated as unset darkness.

The issue is very likely in `pappl/system-loadsave.c` on line 531. However, most other settings are not saved when they are 0.

**Comment by michaelrsweet** [comment]
Yes, this also affects print-speed-default, so I've updated both to output if the corresponding attributes are supported:

[master 528bd54] Save print-speed-default and printer-darkness-configured values if the attributes are supported (Issue #337)

[v1.4.x 977491a] Save print-speed-default and printer-darkness-configured values if the attributes are supported (Issue #337)
