### ISSUE TITLE
vcnet libpappl won't build due to new/renamed APIs httpConnectUri and httpConnectAgain

### ISSUE THREAD

**Issue by ppoirier1** [michaelrsweet/pappl#362]
**Describe the bug**
libpappl2 and testpappl don't build in VS2022 due to the aforementioned missing APIs 

**To Reproduce**
1. Clone pappl and attempt to build the vcnet project

**Expected behavior**
Apps build.

**Screenshots**
![image](https://github.com/user-attachments/assets/7e4a9edd-54d2-48d1-828e-4a60e3bbe281)

**System Information:**
 - OS: Windows 11 22H2
 - IDE: Visual Studio 2022 w/all current updates

**Additional context**
These APIs were added to libcups3 in the past month but the nuget version of CUPS is from last year

**Comment by michaelrsweet** [comment]
Yeah, I need to update the Nuget packages for libcups3. Still working out some OAuth issues then I'll push a 3.0rc1 update of libcups3 to NuGet and do the corresponding updates in the VC projects for PAPPL.

**Comment by michaelrsweet** [comment]
Fixed,
