### ISSUE TITLE
Add LPD support for PAPPL

### ISSUE THREAD

**Issue by zdohnal** [michaelrsweet/pappl#363]
**Is your feature request related to a problem? Please describe.**
It looks like it is common for old Windows print servers in enterprise environment to by accessed by CUPS via LPD protocol instead of Samba - some people probably won't be able to upgrade to newer Windows, so it would be great to have a way how to support them within PAPPL, once LPD is removed from CUPS.

**Describe the solution you'd like**
If the destination is installed with port 515 (queue name might be specified as well), send the data via LPD protocol.

**Comment by michaelrsweet** [comment]
I am really not keen on propagating LPD support in PAPPL. The "legacy" printer applications (that wrap CUPS drivers) already bundle the CUPS LPD backend and so already support LPD that way... That covers all of the PS/PCL office printers you'd be printing to via an old Windows print server...

**Comment by zdohnal** [comment]
Ok, then the plan is to move LPD backend into pappl-retrofit. IIUC currently it uses CUPS LPD backend as it is (it uses symlink to /usr/lib/cups, so it sees backends and filters as CUPS 2.x), so once CUPS removes it, it stops working.

But if the plan would be to move them into pappl-retrofit, then we don't need it in PAPPL. @tillkamppeter is my conclusion correct, Till?
