### ISSUE TITLE
WLS2 UBUNTU 22.04 

### ISSUE THREAD

**Issue by jean202222222** [michaelrsweet/pappl#364]
Hi
**Describe the bug**
make fails with message
Compiling pwg-driver.c...
Linking testmainloop...
Compiling testpappl.c...
testpappl.c: In function ‘test_client’:
testpappl.c:3426:3: warning: implicit declaration of function ‘httpReconnect’; did you mean ‘httpConnect’? [-Wimplicit-function-declaration]
 3426 |   httpReconnect(http, 30000, NULL);
      |   ^~~~~~~~~~~~~
      |   httpConnect
Linking testpappl...
/usr/bin/ld: testpappl.o: in function `test_client':
/home/lelan/pappl/testsuite/testpappl.c:3426: undefined reference to `httpReconnect'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:66: testpappl] Error 1
make[1]: Leaving directory '/home/lelan/pappl/testsuite'
make: *** [Makefile:28: all] Error 1

Best regards

**Comment by michaelrsweet** [comment]
Would help to know what version of PAPPL you are trying to compile.

Note that PAPPL master requires the current libcups master (not the old beta release) to build.

**Comment by jean202222222** [comment]
Hi 1.4.6
i don't understand "the current libcups master (not the old beta release)" How to see what i use?

**Comment by michaelrsweet** [comment]
PAPPL is a library, not a command.

There is a test suite program you can use to play with PAPPL's capabilities (it is in the testsuite directory and is called testpappl) but all it does is convert print jobs to PWG raster and stores the resulting files in a directory. It normally is used to test the various functions of the PAPPL library and isn't meant as a program for users.

**Comment by jean202222222** [comment]
ah sorry! With snap, is it possible to access PAPPL logs?  I see device Epson AL C4100 but it doesn't work. Only PS3... lines written
