### ISSUE TITLE
PAPPL is missing the display of printer options.

### ISSUE THREAD

**Issue by rjgcs** [michaelrsweet/pappl#367]
Why, when using the PAPPL library to develop printer drivers, after users add a printer, the "Printer Options - Printer Features" section is missing in the print dialog window? Conventional printer drivers developed with CUPS would typically display this option in the dialog window. If PAPPL does not support this feature, please let me know. If it does support it, how can I configure it to make this option appear? Please refer to the specific details in the comparison between the two images below.
![0f318bd1469f6161c12354f279f8dccf](https://github.com/user-attachments/assets/cee2df56-deee-4ab8-95b6-621165af10c7)
![c8b9c92961a98859ae37aecbf79c3e38](https://github.com/user-attachments/assets/6fd34ccc-2c2a-4e2f-9660-a400ad427b59)
I personally believe this feature is essential.

**Comment by rjgcs** [comment]
I'm sorry, I should have used screenshots in an English environment to make it clearer for you to understand the issue. I urgently need to solve this problem. Our customer requires the ability to select printer options during print preview, as shown in the screenshot below. Could you please help me check if this issue can be resolved?
![50cbd1c2e8713386dbae1cbb5049f5df](https://github.com/user-attachments/assets/497904f2-70e3-427a-b4dd-39ff885e79e1)
![b274961873ed4715e299022b5a80df22](https://github.com/user-attachments/assets/761a49f2-3250-4838-9f62-8aa36875fd7c)

**Comment by rjgcs** [comment]
Sorry to trouble you again, the effect I want is as shown in the screenshot below. I hope that after setting the printer options on the webpage, the selected option can also be synced and displayed in the print preview popup window. How should I set this up? Could you please provide some guidance on how to achieve this? Thank you very much.
![3ad1c1c4980b17fa0d55a19993bc0ecb](https://github.com/user-attachments/assets/2942f581-b76b-48d2-8c33-67419f3051ef)

**Comment by tangyanli** [comment]
请问是什么系统？以及是什么应用程序(看上去不是基于GTK开发的)？
pappl只是模拟device，至于您在应用程序中选择的printer，应该是driverless自动生成的。Driverless目前
只会为printer生成一些有限的属性，例如size，type，两面，color等。

== translation
What distro is it? And what is the application (It doesn’t seem to be developed based on GTK)?
Pappl just simulates the device. As for the printer you choose in the application, it should be automatically generated by the driverless. Driverless only generates limited attributes for the printer, such as size, type, both sides, color, etc.

**Comment by rjgcs** [comment]
@tangyanli First of all, thank you for your response. I also noticed this issue. I am developing a macOS printing driver based on the PAPPL 1.4.6 project. What I need to achieve is the native CUPS system effect, where the default printer options are also displayed in the print dialog. However, as you mentioned, through the Driverless method, during the process of adding a printer, it seems that the CUPS system internally generates the PPD file via the _ppdCreateFromIPP function (this is inferred from examining the CUPS source code). The generated PPD file only contains basic attributes like color mode and quality, but it doesn't show the preset printer options. However, these options are displayed correctly on the web page provided by the Driverless method.

**Comment by michaelrsweet** [comment]
You are confusing what PAPPL provides with what macOS provides… I have no control over what Apple chooses to support in their UI, so you need to report the issue to them directly.

The printing defaults in the PAPPL web interface will get used when Mac clients print. To get control from the Print dialog, Apple needs to support more of the (IPP) options.
