### ISSUE TITLE
Segfault with hp-printer-app

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#39]
**Describe the bug**
When I build hp-printer-app I get a segfault in the web interface after having created a printer and then try to open the media setup page by clicking the "Media" button.

**To Reproduce**
- "git clone" both PAPPL and hp-printer-app
- Build PAPPL by the usual `./configure; make`
- Build the hp-printer-app with the command line `gcc -o hp-printer-app hp-printer-app.c <PAPPLDIR>/pappl/libpappl.a -ldl -lpthread  -lcups -lavahi-common -lavahi-client -lgnutls -ljpeg -lpng16 -lz -lz -lusb-1.0 -lpam -I. -I<PAPPLDIR>pappl` with `<PAPPLEDIR>` being the source directory of PAPPL.
- Start hp-printer-app in server mode: `./hp-printer-app server`
- With the web interface create a printer with "HP LaserJet" driver, then click the "Media" button. The media configuration page does not open, the app has segfaulted.

**Expected behavior**
The media config page should show up.

**System Information:**
 - OS: Ubuntu Groovy 20.10
 - Browser Chromium Snap as it comes with Ubuntu 20.10
 - Version 85.0.4183.121
 - Printer HP OfficeJet Pro 8730, connected via both USB and network

**Additional context**
gdb backtrace of the core file
```
#0  0x0000557a8e60a7c6 in localize_keyword (bufsize=256, 
    buffer=0x7f2f6e863428 "US Legal", 
    keyword=0x557a8e60f02d "executive_7x10in", attrname=0x557a8e61d356 "media")
    at printer-webif.c:1341
#1  localize_keyword (attrname=0x557a8e61d356 "media", 
    keyword=0x557a8e60f02d "executive_7x10in", 
    buffer=0x7f2f6e863428 "US Legal", bufsize=256) at printer-webif.c:1274
#2  0x0000557a8e60d06d in media_chooser (media=0x7f2f6e862064, 
    name=0x7f2f6e863308 "ready0", title=<optimized out>, 
    driver_data=0x7f2f6e861100, client=0x557a90620e00) at printer-webif.c:1468
#3  _papplPrinterWebMedia (client=0x557a90620e00, printer=<optimized out>)
    at printer-webif.c:1084
#4  0x0000557a8e5fcfe1 in _papplClientProcessHTTP (
    client=client@entry=0x557a90620e00) at client.c:358
#5  0x0000557a8e5fd41a in _papplClientRun (client=0x557a90620e00)
    at client.c:623
#6  0x00007f2f708ed590 in start_thread (arg=0x7f2f6e866640)
    at pthread_create.c:463
#7  0x00007f2f704a2223 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by tillkamppeter** [comment]
@JaiLuthra1, could you also have a look into this?

**Comment by michaelrsweet** [comment]
The media names are wrong. hp-printer-app bug...
