### ISSUE TITLE
Request for ArchLinux user repository (AUR) packaging

### ISSUE THREAD

**Issue by Kerrung** [michaelrsweet/pappl#4]

**Comment by michaelrsweet** [comment]
Well, I had to look that one up. Sorry, I don’t use ArchLinux, and at this point things are really early so I’m not worrying about packaging for any distribution.

**Comment by andyrtr** [comment]
I'm on it. I've prepared a package that will go into our official repo.

**Comment by michaelrsweet** [comment]
Assuming this has been taken care of...
