### ISSUE TITLE
Entries for discovered printers are cryptic

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#40]
**Describe the bug**
I am testing with the HP printer sample app `hp-printer-app`. When adding a new printer in the web interface ([`https://localhost:8000/addprinter`](https://localhost:8000/addprinter)) the discovered printer devices listed under "Devices:" are represented by cryptic, very long strings, where normal end users do not know which one to choose (the best is merge PR #36 ASAP, but manual addition is still often needed).

In case of a discovered network printer the DNS-SD-based URI seems not to get completely decoded, in the list appears `HP\032OfficeJet\032Pro\0328730\032\09108C992\093` instead of `HP OfficeJet Pro 8730 [08C992]`.

For USB printers there are 3 problems:
1. There are 2 identical entries
2. "HP" is duplicate: `USB HP HP OfficeJet Pro 8730 ...`
3. After the model name appears a very long string of digits, like `(05000009000009000009000009000009, 12000, 170000000000000000000000000000)`

As Printer Applications should get the standard way to provide printer drivers they need to be usable also for normal end users, who simply want to print.

**To Reproduce**
Follow the steps to build the hp-printer-app in Issue #39. You will reach the problem described here before it comes to the crash described there.
Start the app as a server: `./hp-printer-app server`.
In a browser open the web interface and click the button to add a printer. Click on the drop-down of "Devices:". Then you see the cryptic entries described above. You need a printer in your network/on your USB.

**Expected behavior**
Clear, user-friendly entries in the "Devices:" drop-down:
- `HP OfficeJet Pro 8730, Network host HOST_NAME (IP)` 
- `HP OfficeJet Pro 8730, USB, Serial No. 12345678`

**System Information:**
Same as in Issue #39

**Comment by tillkamppeter** [comment]
@JaiLuthra1, could you also have a look into this?

**Comment by tillkamppeter** [comment]
When browsing the "Devices:" list in the web interface I get the following error messages in the terminal:
```
E [2020-10-02T20:38:52.454Z] [Device] Unable to get IEEE-1284 device ID: Input/Output Error
E [2020-10-02T20:38:52.454Z] [Device] Unable to get IEEE-1284 device ID: Input/Output Error
E [2020-10-02T20:38:52.456Z] [Device] Unable to get IEEE-1284 device ID: Input/Output Error
```

**Comment by tillkamppeter** [comment]
HP OfficeJet Pro 8730

**Comment by michaelrsweet** [comment]
@tillkamppeter Try the current code in the master branch...

**Comment by tillkamppeter** [comment]
Thank you for your improvement on this.
I have tested now, but not with hp-printer-app, as you did not update this one to your new API changes (please do, or @JaiLuthra1?). I simply ran the "testpappl" app of the PAPPL package itself, clicked "Add Printer" and my printer (connected on both USB and Ethernet) appeared three times, one clearly to be identified as USB ("HP OfficeJet Pro 8730 (USB)"), one marked with the printer's network IP address: "HP OfficeJet Pro 8730 (10.0.0.3)" (is this socket, port 9100?) and a third, being marked as "HP OfficeJet Pro 8730 [08C229]". This looks much better but is not yet perfect.
On the USB entry the serial number (but in human-readable form, some string of 10 or 12 letters and/or numbers) could be useful, so that if someone connects 2 of the same model, he can distinguish them.
The socket entry could also somehow inform that it is actually socket, and not for example LPD.
The third one, "HP OfficeJet Pro 8730 [08C229]", I guess it is IPP, an I right? Should also be marked.
How do you handle IPP/IPPS for an IPP printer here? I suggest simply have one entry using the "better" one, so IPPS if available (this is what I do in the "driverless" utility of cups-filters). Mark it simply as "IPP" for best understandability.
 Also sorting of the listing could improve things, for example checking the UUID of discovered printers to make entries of one physical device being together, or with this even menu/submenu (select discovered printer, then connection type).

**Comment by michaelrsweet** [comment]
@tillkamppeter I thought I had updated hp-printer-app, will double-check.

The second (10.0.0.3) is the same printer detected via SNMP. It *should* be the SNMP machine name (not the IP address) and resolves to socket.

The third is Bonjour/DNS-SD and also resolves to socket.

PAPPL *does not* support IPP printers (why when CUPS can talk to them already?) and doesn't support LPD since basically all printers that support LPD also support socket.

**Comment by michaelrsweet** [comment]
OK, I think I've updated things so that you don't see a bunch of strange entries, and all of them are flagged with the technology used.
