### ISSUE TITLE
Web interface: One can set Borderless Media, but setting not displayed

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#50]
**Describe the bug**
Under the media settings of a printer you have checkboxes for "Borderless". Checking it and saving the settings actually sets the printer to borderless (one can see in state file or when printing) but when opening the media settings the checkbox never appears checked, indpendent of the setting. The box should be checked when the media is already set to borderless. Also the Printing defaults should show the media not only with size and type but also with borderless status.

**To Reproduce**
Add a printer, must have capability of borderless printing (like the testpappl which comes with PAPPL). Enter media screen, set a media size and mark the borderless checkbox. Go to printing defaults. Only your selected size and media type is shown, no hint that you selcted borderless. Go back to media and you see that borderless is not checked, though it is active.

**Expected behavior**
When getting to the media settings again, the borderless checkbox should be checked when you have set borderless before. On Printing defaults the media dropdown should show whether the media is borderless.

**Comment by michaelrsweet** [comment]
[master b1820d4] Fix borderless check box (Issue #50)
