### ISSUE TITLE
Web interface needs a driver-auto-select button, "add" subcommand a driver auto-select option

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#56]
**Is your feature request related to a problem? Please describe.**
Currently, if you add a printer on a Printer Application you always have to select the driver manually, both in the web interface and with the "add" command line subcommand.
This is not such a big problem with hp-printer-app with only 3 drivers to choose from but gets awkward with a Printer Application like ps-printer-app with ~4000 drivers (= printer models) to choose from. The long list comes in handy if your printer is not explicitly under these 4000 and you want to select a similar one, but if you want to quickly add a discovered printer, an "Automatically Select Driver" button wold be very helpful.
Also on the command line one could have the possibility to supply `-m auto` for the Printer Application automatically to select the best driver for the discovered printer (as supplied by `-v ...`.
To implement this, the Printer Application can simply call the autoadd callback function with the device ID of the printer, getting back the name of the best driver. If the printer is unsupported the autoadd callback returns NULL and so the "add" subcommand could return an error message to the user and not add the printer. In case of the web interface an error message telling that the printer is not supported would be shown.

**Describe the solution you'd like**
Web interface: Add "Automatically Select Driver" button to the page for adding a printer. Then user does not need to select driver from drop-down list.
Command line: With the "add" subcommand allow also `-m auto` for automatic driver selection.
Use autoadd callback function to determine the best driver.

**Describe alternatives you've considered**
Add driver named "auto" as very first entry to the driver list of the Printer Application (so that the long list of drivers starts with "Automatic Selection" and also `-m auto` with the "add" subcommand is accepted). If the user selects this when adding a printer the driver callback ([ps-callback() in ps-printer-app.c](https://github.com/OpenPrinting/ps-printer-app/blob/8bf45c81da1287cb80421a8e7ea4e9e1e2b4347f/ps-printer-app.c#L282)) has to determine which driver actually to choose, but this callback does not get the device ID of the printer and so this is not possible.

**Comment by michaelrsweet** [comment]
The driver list now includes the IEEE-1284 device ID, so it should be possible to auto-detect with that if we can get the .

The autoadd callback (for the mainloop API) is a separate thing for printers that should be auto-added (vs. auto-detecting the driver for a selected device).

**Comment by michaelrsweet** [comment]
@tillkamppeter I think we have this covered now with the auto-add callback and "auto" driver name, right?

**Comment by tillkamppeter** [comment]
Yes, this is solved now.
