### ISSUE TITLE
Media trays and option defaults broken in web interface

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#57]
**Describe the bug**
I am developing the [PostScript Printer Application](https://github.com/OpenPrinting/ps-printer-app/) and some days ago it was correctly working, in terms of adding a printer, selecting the driver (= model) and then you could set media sizes and types, and also borderless (this made me report issue #50) for the printer's trays (my HP OfficeJet Pro 8730 showed two trays) and you also could set option default like duples or print quality, and actually print in the end, with the settings obeyed by the printer.
Now, with the current PAPPL no trays show any more, and also some options in the "Printing Defaults" are missing. The problem seems to be some changes in PAPPL, as I did not do any changes in populating the driver data structure, also the PPD file from which I take the info for populating the driver data was always the same.
Restarting the Printer Application always shows the same result, the trays and options missing.
Below is debug log output of the starting of the Printer Application with the printer already added, beginning from loading the state file (skipping the building of the driver list from ~4000 PPD files). It shows that the printer entry loads its (correct) PPD file, and after that it seems that PAPPL verifies the driver data as populated by the ps_callback() function (the driver callback) and finds some problems which not actually are problems:
```
D [2020-10-30T23:10:44.112Z] Using PPD /snap/ps-printer-app/current/usr/share/ppd//hplip-ps-ppds.tar.gz:./hp-officejet_pro_8730-ps.ppd: HP OfficeJet Pro 8730 Postscript (recommended)
D [2020-10-30T23:10:44.112Z] [Printer test] identify-actions-default=0x0004
D [2020-10-30T23:10:44.112Z] [Printer test] media-default=na_letter_8.5x11in
D [2020-10-30T23:10:44.112Z] [Printer test] orientation-requested-default=7(none)
D [2020-10-30T23:10:44.112Z] [Printer test] print-color-mode-default=auto(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] print-content-default=auto(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] print-quality-default=4(normal)
D [2020-10-30T23:10:44.112Z] [Printer test] print-scaling-default=auto(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] printer-resolution-default=600x600dpi
D [2020-10-30T23:10:44.112Z] [Printer test] sides-default=one-sided(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] Driver uses extension data (0x5593c4d951e0) and no delete function.
F [2020-10-30T23:10:44.112Z] [Printer test] Driver does not provide required raster printing callbacks.
W [2020-10-30T23:10:44.112Z] [Printer test] Driver does not support a self-test page.
D [2020-10-30T23:10:44.112Z] [Printer test] Driver reports ppm 24.
D [2020-10-30T23:10:44.112Z] [Printer test] Driver reports ppm_color 24.
W [2020-10-30T23:10:44.112Z] [Printer test] Driver does not provide printer icons, using defaults.
```
First one sees that the default settings got correctly extracted from the PPD file (by ps_callbck()), then it says "Driver does not provide required raster printing callbacks", but these are not actually needed as this is a non-Raster driver, the output is PostScript. Is there any mechanism of the tests being considered failed and so the driver data not being held by the system and made available in the web interface?
The state file content is the following:
```
DNSSDName PS Printer App (4187D4)
Contact
DefaultPrinterID 1
NextPrinterID 7
UUID urn:uuid:d9bfb18e-69d9-37d8-5de6-c65f4f4187d4
<Printer did="MFG:HP;MDL:HP OfficeJet Pro 8730;CMD:PCL5c,PCLXL,POSTSCRIPT,NATIVEOFFICE" driver="hp--officejet-pro-8730--en" id="6" name="test" uri="usb://HP/HP%20OfficeJet%20Pro%208730?serial=CN783F60W1">
Contact
MaxActiveJobs 0
MaxCompletedJobs 100
NextJobId 1
ImpressionsCompleted 0
media-col-default
</Printer>
```
The printer entry is there, the driver name "`hp--officejet-pro-8730--en`" is derived from the PPD file, a naming scheme robust agains new PPD files being added to the Snap. One sees that there are no default option settings or media selections in the file.

**To Reproduce**
Download the source code of the [PostScript Printer Application](https://github.com/OpenPrinting/ps-printer-app/), build the Snap (it takes automatically care of using the current GIT snapshots of PAPPL and cups-filters), and install it. Connect a printer to your system or to the network. Then run
```
ps-printer-app -o log-level=debug server &
```
Add a printer via the "Add Printer" page of the web interface, simply select the "Generic PostScript Printer" as driver if your printer is not in the list. Click the "Media" or "Printing Defaults" button and you will see screens like shown in the screenshots below. Now media trays to select paper sizes for, missing options.

**Expected behavior**
As before, the trays and options should show.

**Screenshots**
Media page: Nothing is displayed, before two trays were shown (otherwise I had not been able to report issue #50)
![Screenshot from 2020-10-31 00-19-54](https://user-images.githubusercontent.com/1244825/97764432-f6db6e80-1b0e-11eb-8575-c33def74d4e2.png)

Option defaults page: No media selectable, double-sided option missing
![Screenshot from 2020-10-31 00-20-00](https://user-images.githubusercontent.com/1244825/97764446-00fd6d00-1b0f-11eb-8f2c-aa1cfb2b6ba7.png)

**System Information:**
- Ubuntu, Focal Fossa 20.04 to build Snaps, problem occurs on both 20.04 and 20.10.
- PAPPL, cups-filters, and ps-printer-app are current GIT snapshots.

**Additional context**
```
I [2020-10-30T23:10:43.868Z] Loading system state from '/tmp/ps_printer_app.state'.
D [2020-10-30T23:10:43.868Z] Registering DNS-SD name 'PS Printer App (4187D4)' on 'till-x1yoga.local'
I [2020-10-30T23:10:43.870Z] Printer 'test' at resource path '/ipp/print/test'.
D [2020-10-30T23:10:44.112Z] Using PPD /snap/ps-printer-app/current/usr/share/ppd//hplip-ps-ppds.tar.gz:./hp-officejet_pro_8730-ps.ppd: HP OfficeJet Pro 8730 Postscript (recommended)
D [2020-10-30T23:10:44.112Z] [Printer test] identify-actions-default=0x0004
D [2020-10-30T23:10:44.112Z] [Printer test] media-default=na_letter_8.5x11in
D [2020-10-30T23:10:44.112Z] [Printer test] orientation-requested-default=7(none)
D [2020-10-30T23:10:44.112Z] [Printer test] print-color-mode-default=auto(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] print-content-default=auto(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] print-quality-default=4(normal)
D [2020-10-30T23:10:44.112Z] [Printer test] print-scaling-default=auto(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] printer-resolution-default=600x600dpi
D [2020-10-30T23:10:44.112Z] [Printer test] sides-default=one-sided(0x0001)
D [2020-10-30T23:10:44.112Z] [Printer test] Driver uses extension data (0x5593c4d951e0) and no delete function.
F [2020-10-30T23:10:44.112Z] [Printer test] Driver does not provide required raster printing callbacks.
W [2020-10-30T23:10:44.112Z] [Printer test] Driver does not support a self-test page.
D [2020-10-30T23:10:44.112Z] [Printer test] Driver reports ppm 24.
D [2020-10-30T23:10:44.112Z] [Printer test] Driver reports ppm_color 24.
W [2020-10-30T23:10:44.112Z] [Printer test] Driver does not provide printer icons, using defaults.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/icon-sm.png'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/icon-md.png'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/icon-lg.png'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/cancel'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/cancelall'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/delete'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/config'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/jobs'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/media'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/test/printing'.
I [2020-10-30T23:10:44.112Z] Listening for connections on '/tmp/ps-printer-app1000.sock'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/favicon.png'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/navicon.png'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/style.css'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/addprinter'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/config'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/network'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/security'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/tls-install-crt'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/tls-new-crt'.
D [2020-10-30T23:10:44.112Z] Adding resource for '/tls-new-csr'.
I [2020-10-30T23:10:44.112Z] Starting system.
D [2020-10-30T23:10:45.114Z] Registering DNS-SD name 'PS Printer App (4187D4)' on 'till-x1yoga.local'
I [2020-10-30T23:10:45.119Z] Saving system state to '/tmp/ps_printer_app.state'.
I [2020-10-30T23:11:23.843Z] [Client 1] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.843Z] [Client 2] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.843Z] [Client 1] Starting HTTPS session.
I [2020-10-30T23:11:23.843Z] [Client 2] Starting HTTPS session.
E [2020-10-30T23:11:23.846Z] [Client 2] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:23.846Z] [Client 2] Closing connection from 'localhost'.
E [2020-10-30T23:11:23.847Z] [Client 1] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:23.847Z] [Client 1] Closing connection from 'localhost'.
I [2020-10-30T23:11:23.860Z] [Client 3] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.860Z] [Client 3] Starting HTTPS session.
E [2020-10-30T23:11:23.863Z] [Client 3] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:23.863Z] [Client 3] Closing connection from 'localhost'.
I [2020-10-30T23:11:23.864Z] [Client 4] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.864Z] [Client 4] Starting HTTPS session.
I [2020-10-30T23:11:23.867Z] [Client 4] Connection now encrypted.
I [2020-10-30T23:11:23.868Z] [Client 4] GET https://localhost:8000/ HTTP/1.1
I [2020-10-30T23:11:23.868Z] [Client 4] OK text/html 0
I [2020-10-30T23:11:23.868Z] [Client 4] Closing connection from 'localhost'.
I [2020-10-30T23:11:23.913Z] [Client 5] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.914Z] [Client 5] Starting HTTPS session.
E [2020-10-30T23:11:23.917Z] [Client 5] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:23.917Z] [Client 5] Closing connection from 'localhost'.
I [2020-10-30T23:11:23.920Z] [Client 6] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.921Z] [Client 7] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.921Z] [Client 8] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.922Z] [Client 6] Starting HTTPS session.
I [2020-10-30T23:11:23.922Z] [Client 7] Starting HTTPS session.
I [2020-10-30T23:11:23.922Z] [Client 8] Starting HTTPS session.
E [2020-10-30T23:11:23.924Z] [Client 6] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:23.924Z] [Client 6] Closing connection from 'localhost'.
I [2020-10-30T23:11:23.925Z] [Client 9] Accepted connection from 'localhost'.
E [2020-10-30T23:11:23.925Z] [Client 7] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:23.925Z] [Client 7] Closing connection from 'localhost'.
I [2020-10-30T23:11:23.926Z] [Client 9] Starting HTTPS session.
I [2020-10-30T23:11:23.927Z] [Client 10] Accepted connection from 'localhost'.
I [2020-10-30T23:11:23.927Z] [Client 10] Starting HTTPS session.
I [2020-10-30T23:11:23.929Z] [Client 8] Connection now encrypted.
I [2020-10-30T23:11:23.930Z] [Client 8] GET https://localhost:8000/style.css HTTP/1.1
I [2020-10-30T23:11:23.930Z] [Client 8] OK text/css 8671
I [2020-10-30T23:11:23.932Z] [Client 9] Connection now encrypted.
I [2020-10-30T23:11:23.932Z] [Client 10] Connection now encrypted.
I [2020-10-30T23:11:23.932Z] [Client 9] GET https://localhost:8000/test/icon-md.png HTTP/1.1
I [2020-10-30T23:11:23.935Z] [Client 9] OK image/png 6292
I [2020-10-30T23:11:23.932Z] [Client 8] GET https://localhost:8000/navicon.png HTTP/1.1
I [2020-10-30T23:11:23.936Z] [Client 8] OK image/png 3359
I [2020-10-30T23:11:26.006Z] [Client 9] GET https://localhost:8000/test/ HTTP/1.1
I [2020-10-30T23:11:26.006Z] [Client 9] OK text/html 0
I [2020-10-30T23:11:26.006Z] [Client 9] Closing connection from 'localhost'.
I [2020-10-30T23:11:26.039Z] [Client 8] GET https://localhost:8000/style.css HTTP/1.1
I [2020-10-30T23:11:26.039Z] [Client 8] OK text/css 8671
I [2020-10-30T23:11:27.692Z] [Client 8] GET https://localhost:8000/test/media HTTP/1.1
I [2020-10-30T23:11:27.692Z] [Client 8] OK text/html 0
I [2020-10-30T23:11:27.692Z] [Client 8] Closing connection from 'localhost'.
I [2020-10-30T23:11:27.739Z] [Client 10] GET https://localhost:8000/navicon.png HTTP/1.1
I [2020-10-30T23:11:27.739Z] [Client 10] Not Modified
I [2020-10-30T23:11:27.740Z] [Client 10] Closing connection from 'localhost'.
I [2020-10-30T23:11:29.546Z] [Client 11] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.546Z] [Client 12] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.547Z] [Client 11] Starting HTTPS session.
I [2020-10-30T23:11:29.547Z] [Client 12] Starting HTTPS session.
E [2020-10-30T23:11:29.549Z] [Client 12] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:29.549Z] [Client 12] Closing connection from 'localhost'.
E [2020-10-30T23:11:29.550Z] [Client 11] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:29.550Z] [Client 11] Closing connection from 'localhost'.
I [2020-10-30T23:11:29.559Z] [Client 13] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.560Z] [Client 13] Starting HTTPS session.
I [2020-10-30T23:11:29.564Z] [Client 13] Connection now encrypted.
I [2020-10-30T23:11:29.564Z] [Client 13] GET https://localhost:8000/test/ HTTP/1.1
I [2020-10-30T23:11:29.564Z] [Client 13] OK text/html 0
I [2020-10-30T23:11:29.564Z] [Client 13] Closing connection from 'localhost'.
I [2020-10-30T23:11:29.601Z] [Client 14] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.602Z] [Client 14] Starting HTTPS session.
I [2020-10-30T23:11:29.603Z] [Client 15] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.604Z] [Client 15] Starting HTTPS session.
E [2020-10-30T23:11:29.606Z] [Client 14] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:29.606Z] [Client 14] Closing connection from 'localhost'.
E [2020-10-30T23:11:29.606Z] [Client 15] Unable to encrypt connection: A TLS fatal alert has been received.
I [2020-10-30T23:11:29.606Z] [Client 15] Closing connection from 'localhost'.
I [2020-10-30T23:11:29.607Z] [Client 16] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.607Z] [Client 17] Accepted connection from 'localhost'.
I [2020-10-30T23:11:29.607Z] [Client 16] Starting HTTPS session.
I [2020-10-30T23:11:29.608Z] [Client 17] Starting HTTPS session.
I [2020-10-30T23:11:29.613Z] [Client 16] Connection now encrypted.
I [2020-10-30T23:11:29.613Z] [Client 17] Connection now encrypted.
I [2020-10-30T23:11:29.614Z] [Client 16] GET https://localhost:8000/style.css HTTP/1.1
I [2020-10-30T23:11:29.614Z] [Client 17] GET https://localhost:8000/test/icon-md.png HTTP/1.1
I [2020-10-30T23:11:29.614Z] [Client 17] OK image/png 6292
I [2020-10-30T23:11:29.614Z] [Client 16] OK text/css 8671
I [2020-10-30T23:11:59.642Z] [Client 16] Closing connection from 'localhost'.
I [2020-10-30T23:11:59.642Z] [Client 17] Closing connection from 'localhost'.
```

**Comment by michaelrsweet** [comment]
@tillkamppeter Without raster callbacks, the default print filters (including PWG/Apple raster support, required for IPP Everywhere conformance) won't work. You need to implement them, even for PostScript, even if that won't be optimal.

**Comment by tillkamppeter** [comment]
My ps-printer-app supports Raster and JPEG input, it uses filter functions of cups-filters, which take in the Raster input as a whole and stream out PostScript, with all needed code snippets of the PPD inserted. So the Printer Application is actually working as intended and fulfilling the IPP Everywhere requirements.
With the use of the filter functions I re-use as much of existing code as possible to support the legacy PostScript printers and also prepare the easy retro-fit of other existing classic CUPS drivers, especially ones which are not maintained any more, where we do not have access to the printers to test a complete re-write, or even closed-source drivers.
The retro-fit of classic CUPS drivers is needed for the transition of OS distributions from classic CUPS packaging to the CUPS Snap, as the snapped CUPS does not support classic CUPS drivers.
So I appreciate if the requirement of definition of the raster functions by PAPPL could be dropped, you could better check whether all required input formats are supported.

**Comment by michaelrsweet** [comment]
@tillkamppeter raster files are streamed, never spooled. So you really do need to implement the raster callbacks, at least for that.

**Comment by tillkamppeter** [comment]
For new drivers implementing raster callbacks is OK, as the developer, ideally the manufacturer, has the printer for testing during the development. Same for Gutenprint which Sambhav will complete soon.

In my situation I want to retro-fit classic CUPS drivers without modifying their code and often these classic drivers call Ghostscript taking in PDF (or PostScript) as input and Ghostscript then produces the printer-specific raster output using a built-in driver. If I simply include Ghostscript in the Snap and and feed PostScript or PDF into it (JPG or PWG/Apple Raster input I convert to PDF with a filter function) I can have good confidence that the printer still prints with the (now unmaintained) built-in Ghostscript driver.
If I have to read the Ghostscript driver's source code, try to understand it at my best to write PAPPL raster callbacks which are supposed to do the same thing as the Ghostscript driver does the risk that this does not work is immensely high, especially as I am not such a great Ghostscript expert. Also with the hundreds of drivers (see driver list on OpenPrinting we site) it will take me months or even years to convert all this.
Simply taking Ghostscript into the Snap and using it as it is will allow me to create a Foomatic Printer Application covering all the Ghostscript drivers in a few days after having completed the PostScript Printer Application, as it will get very similar.
Another point are closed-source CUPS filters which also cannot get converted into a set of raster callback functions but they can get integrated into a Printer Application Snap, if needed with a chroot.
Also high-level graphics input (PDF or PostScript) to be printed as high-level graphics (PostScript or PCL-XL) should not go through a raster graphics interim step, to make use of the high-level graphics capabilities of the printer, to assure that also older PostScript printers work (with low memory, can print PostScript text page but not a full page raster image making up the same text page), to reduce resource consumption on the machine running the Printer Application.

**Comment by michaelrsweet** [comment]
@tillkamppeter Your raster callbacks can produce PostScript (with the appropriate PPD commands) which can be sent to Ghostscript (or whatever is consuming it) - there is no need to integrate/rewrite Ghostscript drivers in your printer application.

**Comment by tillkamppeter** [comment]
If you mean that for a Ghostscript driver the Raster callbacks should be used, this would mean that the Postscript fed into Ghostscript is always a raster-based PostScript, consisting of pages with embedded raster graphics. This could make sense if the input format is PWG/Apple Raster or JPEG. If the input is PDF it would be awkward to convert the PDF to raster first (either by the Printer Application or by the CUPS which delivers the jobs to the Printer Application), only that the raster callbacks convert that to PostScript. This is even worse if there is no Ghostscript when we print on a PostScript Printer with the PostScript Printer Application, as some older models are not able to hold a full raster page but could print the original PDF if it arrives as PostScript text/high-level graphics. Therefore I want to have the direct conversion of PDF to PostScript for PostScript printers and the direct feeding of PDF into Ghostscript for Ghostscript drivers.
For calling Ghostscript in raster callbacks, is it the right way that I create a data structure as device data and assign a pointer to the device via papplDeviceSetData() and access it from all raster callbacks via papplDeviceGetData(), then let the rstartjob() call back fire up Ghostscript in a fork put the input file descriptor into the data structure, pipe the output to the device, and then all further raster callbacks feed into the input file descriptor available through the data structure?
Can I continue with my ps_filter() callback for jobs with high-level graphics input (PostScript, PDF)?

**Comment by michaelrsweet** [comment]
@tillkamppeter Please read my prior comments.

The raster callbacks are used as the default rasterization path for JPEG and PNG - if you have a direct JPEG or PNG imaging filter defined, those will be used instead.

Since PWG and Apple raster data is always streamed, PAPPL always uses the raster callbacks.

So for your PS printer application, the raster callbacks will be used for PWG and Apple raster content, and your PS filters will be used for other file formats.

**Comment by tillkamppeter** [comment]
Thanks for the explanation.
I have now added raster callbacks to the PostScript Printer Application:
https://github.com/OpenPrinting/ps-printer-app/commit/2173c5492
