### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/pappl#58]
Add support for localization of the web interface using any string resource files that are added.

----------

Breaking this down into sub-tasks:

- [x] Add `pappl_loc_t` type and structure to hold per-printer localization information.
- [x] Add `cups_array_t *localizations` array to `pappl_system_t` structure to cache the various localizations.
- [x] Add `pappl_loc_t *papplSystemFindLoc(pappl_system_t *system, pappl_printer_t *printer, const char *language)`, `papplLocFormatString(pappl_loc_t *loc, char *buffer, size_t bufsize, const char *key, ...)`, and `const char *papplLocGetString(pappl_loc_t *loc, const char *key)` APIs, plus corresponding private functions `_papplLocCreate` and `_papplLocDelete`.
- [x] Add `pappl_loc_t *papplClientGetLoc(pappl_client_t *client)` API to return the localization associated with the client's `Accept-Language` header.
- [x] Update `papplClientHTMLPrintf` and `papplClientHTMLPuts` to try localizing their inputs using the (cached) localization info and to set/restore the POSIX locale so that numbers are formatted properly.
- [x] Add base localizations for EFIGS
- [ ] Add unit tests

Might be able to internally base the caching on the strings files we are pulling instead of just on the printer since many printer applications won't use per-printer localization files but instead set them at the system level.

**Comment by tillkamppeter** [comment]
Currently vendor options look ugly:
![Screenshot from 2020-11-16 00-07-24](https://user-images.githubusercontent.com/1244825/99199502-e2020a80-279f-11eb-89a1-56b314099207.png)
Option/choice names are the human-readable strings of the PPD file "translated" to IPP keyword syntax. One understands them but real human-readable strings in the web interface would be great.

**Comment by michaelrsweet** [comment]
Breaking this down into sub-tasks:

- [ ] Add `pappl_loc_t` type and structure to hold per-printer localization information.
- [ ] Add `cups_array_t *localizations` array to `pappl_system_t` structure to cache the various localizations.
- [ ] Add `pappl_loc_t *papplLocFind(pappl_system_t *system, pappl_printer_t *printer, const char *language)`, `papplLocFormatString(pappl_loc_t *loc, char *buffer, size_t bufsize, const char *key, ...)`, and `const char *papplLocGetString(pappl_loc_t *loc, const char *key)` APIs, plus corresponding private functions `_papplLocCreate` and `_papplLocDelete`.
- [ ] Add `pappl_loc_t *papplClientGetLocalization(pappl_client_t *client)` API to return the localization associated with the client's `Accept-Language` header.
- [ ] Update `papplClientHTMLPrintf` and `papplClientHTMLPuts` to try localizing their inputs using the (cached) localization info and to set/restore the POSIX locale so that numbers are formatted properly.

Might be able to internally base the caching on the strings files we are pulling instead of just on the printer since many printer applications won't use per-printer localization files but instead set them at the system level.

**Comment by michaelrsweet** [comment]
All done.
