### ISSUE TITLE
With PWG/Apple Raster input papplJobCreatePrintOptions() is called with num_pages = 0, clobbering the Duplex default setting

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#60]
**Describe the bug**
In my PostScript Printer Application I set long-edge duplex as default in the web interface. PDF and PostScript input files get correctly printed double sided. To prepare these jobs I call the `papplJobCreatePrintOptions()` function of PAPPL in the `ps_filter()` function in `ps-printer-app.c`, with `num_pages` set to `INT_MAX`, as I do not know beforehand how many pages my PDF or PostScript file has.
If I send a PWG/Apple Raster job, PAPPL calls the `papplJobCreatePrintOptions()` function in the `_papplJobProcessRaster()` function, but if the input stream has no number of pages info, it uses 0 for `num_pages`. This does not stop PAPPL from printing the whole job with any number of pages, but it breaks the default setting for duplex.
`papplJobCreatePrintOptions()` sets the duplex option for the job as follows:
```
  // sides
  if ((attr = ippFindAttribute(job->attrs, "sides", IPP_TAG_KEYWORD)) != NULL)
    options->sides = _papplSidesValue(ippGetString(attr, 0, NULL));
  else if (printer->driver_data.sides_default != PAPPL_SIDES_ONE_SIDED && options->num_pages > 1)
    options->sides = printer->driver_data.sides_default;
  else
    options->sides = PAPPL_SIDES_ONE_SIDED;
```
If `num_pages` is 0 or 1, the default `sides` is overridden and always `PAPPL_SIDES_ONE_SIDED` selected, due to the `&& options->num_pages > 1`. If you want to set `num_pages` to 0 to tell that the actual number of pages is not known, you should use `&& options->num_pages != 1` instead. Or call `papplJobCreatePrintOptions()` with `INT_MAX` to tell that the number of pages is unknown.

**To Reproduce**
Create a PWG/Apple Raster file WITHOUT number of pages in the first page's header but with more than one page, the Raster files of cups-filters (I used the `gstoraster` filter) generates such files. In the PostScript Printer Application (any other should show the problem, too) create a printer and set the default for 2-sided printing to one of the "On" choices. Print your Raster file with this printer, not specifying the "sides" option on the command line. The printout comes out single-sided. Print a multi-page PDF file and the printout is correctly double-sided.

There should be a reserved value for `num_pages` to tell that the number of pages is unknown, can be 0, -1, or INT_MAX, and it should be mentioned in the source code and in the documentation.

**Expected behavior**
All multi-page jobs correctly double-sided, independent of input format.

**System Information:**
 - Ubuntu 20.10 Groovy
 - Current GIT snapshots of ps-printer-app, PAPPL, and cups-filters

**Comment by michaelrsweet** [comment]
[master a9cacf9] Make sure an unknown number of pages doesn't disable duplex printing (Issue #60)
