### ISSUE TITLE
Show (human-readable) driver names for print queues

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#67]
**Is your feature request related to a problem? Please describe.**
In the web interface of PAPPL there is no information shown about which driver (or make/model) of the Printer Application a printer set up in it is actually using, neither on the front page, nor on the printer's main page, nor on the printer's configuration pages (media, option defaults, ...).
Each driver (in the drivers list, `pappl_pr_driver_t`) has a machine-readable and a human-readable name, in the HP Printer Application it is for example "hp_generic" and "Generic PCL", in the PostScript Printer Application the human-readable name is make/model from the PPD and the machine-readable one is make/model but normalized to lower-case-only and no spaces.
I would like to have the human-readable driver name shown along with each print queue in the web interface, on the front page, on the printer's main page and on the printer's configuration pages.

**Additional context**
Which one is the HP OfficeJet Pro, which the Sharp, and which the Generic Printer?
![Front page of PostScript Printer Application with 3 printers](https://user-images.githubusercontent.com/1244825/98844133-2f9f1000-244c-11eb-984d-4086595404ca.png)
State file:
[ps_printer_app.state.txt](https://github.com/michaelrsweet/pappl/files/5525756/ps_printer_app.state.txt)

**Comment by michaelrsweet** [comment]
It is up to the driver callback to place whatever string is desired in the "make_and_model" string. That is the only thing that will be displayed on the web interface as the point of PAPPL is NOT do expose driver-specific crap but instead to provide an interoperable, functional printing interface.

**Comment by tillkamppeter** [comment]
Yes, this would be enough, but, unfortunately, it does not work for me. In my driver callback, `ps_callback()` I actually populate the `make_and_model` field, with the NickName of the PPD file:
```
  // Make and model
  strncpy(driver_data->make_and_model,
	  ppd->nickname,
	  sizeof(driver_data->make_and_model));
```
But in the web interface this information does not appear.

**Comment by michaelrsweet** [comment]
The printer header will soon include the queue name (again) and the make and model (if it doesn't match the queue name).
