### ISSUE TITLE
Add freely usable data pointer to "pappl_pr_driver_t" data structure

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#68]
**Is your feature request related to a problem? Please describe.**
In my PostScript Printer Application I include PostScript Printer PPD files in the Snap, each PPD makes up a driver in the Printer Application. When a print queue is set up the appropriate PPD file is read and the `pappl_pr_driver_t` is appropriately populated.
The PPD file options not covered by IPP/PAPPL I want to add as vendor options. In addition to the IPP names for the options and choices and human-readable names (Issue #66) I also want to add some extra data needed for the print job execution.
For this I would simple need a freely usable data pointer in the `pappl_pr_driver_t` data structure which I could let point to my own data structure containing the extra data.

**Describe the solution you'd like**
A simple, freely usable data pointer in the `pappl_pr_driver_t` data structure.

**Comment by michaelrsweet** [comment]
This already exists and is called "extension".
