### ISSUE TITLE
Web interface: Button/Link to return to printer's main page from printer's config pages, also show print queue name on the config pages

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#69]
**Describe the solution you'd like**
Each printer has a main page: `https://localhost:8000/test/`:
![Printer's main page](https://user-images.githubusercontent.com/1244825/98846306-2d8a8080-244f-11eb-8ced-529594067368.png)
and configuration pages, for "Media", "Printing Defaults", and "Jobs" (`https://localhost:8000/test/media`, `https://localhost:8000/test/printing`, `https://localhost:8000/test/jobs`). perhaps there are actually more. Here is the "Printing Defaults" page:
![Printing Defaults page](https://user-images.githubusercontent.com/1244825/98846790-c1f4e300-244f-11eb-8db2-0b09ddbc4d67.png)
What is missing on the configuration pages is a button or link which leads back to the printer's main page. The icon at the very top leads only to main page of the whole Printer Application.
In addition, on the configuration pages the print queue's name is missing.

**Comment by tillkamppeter** [comment]
Even on the printer's main page the print queue name is missing.

**Comment by michaelrsweet** [comment]
Fixed (regression from prior web interface changes...)
