### ISSUE TITLE
Provide device ID to driver callback

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#70]
**Describe the solution you'd like**
Driver callbacks are called with the following scheme currently:
```
typedef bool (*pappl_pr_driver_cb_t)(pappl_system_t *system, const char *driver_name, const char *device_uri, pappl_pr_driver_data_t *driver_data, ipp_t **driver_attrs, void *data);
```
As I am creating the PostScript Printer Application supporting ~4000 printer models (information taken from ~4000 manufacturer-supplied PPD files), each of them listed as one driver in the Printer Application it can be awkward for the user to pick the correct model from the list when creating the printer. So I want to add an "auto" driver appearing as the very first item in the driver list, before the ~4000 per-model entries.
If the user selects "auto", the driver callback is supposed to auto-select the printer model.  With the above call scheme the driver callback only gets the device URI from the printer device, not the device ID. From the device URI one cannot look up the device ID and also only some device IDs (USB and DNS-SD, the latter only if the user did not muck up the printer-internal service name) contain make and model info. With make and model info I could easily chooce the correct driver (PPD in the PostScript Printer Application).
Therefore I would like to ask you whether you could change the call scheme, adding the device ID. This can make many Printer Applications much more user-friendly.

**Comment by michaelrsweet** [comment]
[master 93a8077] Add device ID string to driver callback (Issue #70)

**Comment by tillkamppeter** [comment]
Thank you very much, I have added the printer model auto-selection (driver "auto") to the PostScript Printer Application now.
