### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by acjbrouwer** [michaelrsweet/pappl#71]
When reading the README to figure out what PAPPL does, I initially read the ambiguous line

_PAPPL provides access to the printer via its embedded IPP Everywhere™ service_

as _its_ pertaining to _the printer_ instead of _PAPPL_. A small rephrasing should make things clearer.

**Comment by michaelrsweet** [comment]
@acjbrouwer Let me know what you think...

[master 3543dbf] Clean up README file, with clarifications for what PAPPL does (Issue #71)

**Comment by acjbrouwer** [comment]
Thanks, it reads without confusion now. Interesting, did not know before that it possible to  link via a numbered list of URLs in the markdown.
