### ISSUE TITLE
DNS-SD-discovered devices have no device IDs

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#73]
**Describe the bug**
For automatically adding printers with the `autoadd` subcommand but also for drivers automatically adapting to special properties of different printer models the printer's device ID is essential.
Working on a model auto-selection feature (no need to find your printer under ~4000 supported models) in my PostScript Printer Application (`ps_autoadd()` function, also used for the `autoadd` subcommand, "Automatic Selection" in the driver list of the web interface) I have found out that it works only when selecting a USB or SNMP-discovered socket entry under the discovered printers, not when using the DNS-SD-based entry.
Looking for the reason I have discovered that devices discovered on USB or via SNMP come with a device ID, DNS-SD-discovered devices are missing the device ID.
Obtaining a device ID for a DNS-SD-discovered device is easy, the printer does not to get polled and woken up for it.
Note that a device ID should contain MFG, MDL, and CMD fields, the latter for assigning a generic driver or for situations like "is the PostScript add-on module installed?").
First look for "usb_MFG", "usb_MDL", and "usb_CMD" entries in the TXT record, each of them which you find you can directly fill into the corresponding field of the device ID. After that you fill the remaining fields with information derived from the "ty", "product", and "pdl" fields appropriately dissected and converted.
One could think that the device URI which is based on the DNS-SD service name of the printer also could be used to extract make and model info, but
- Only if the printer's service name is still the factory default and not modified in the printer's web interface it contains make and model names and even this is not 100% safe
- We cannot derive the printer's PDLs from the device URI/the service name, so no way to assign generic drivers or check presence of an add-on

**To Reproduce**
Have a network PostScript printer, with socket printing discoverable by DNS-SD available. In the web interface of the PostScript Printer Application select the DNS-SD-based entry under the discovered printers and as driver "Automatic Selection". The new printer will not get created.
If selecting the SNMP-based entry under the discovered printers, the printer will get added, if not an explicitly supported model, as a "Generic PostScript Printer". Also when connecting the printer via USB and selecting the USB-based entry, the printer will get added.
The same should happen (but I did not test) with a PCL printer and the HP PCL Printer Application.

**System Information:**
 - As usual, Ubuntu 20.10 Groovy and the current GIT snapshots of PAPPL, cups-filters, and the PostScript Printer Application

**Comment by tillkamppeter** [comment]
I have reviewed and tested your fix on this. Unfortunately, it does not work for me. There are two issues on it:
1. Not understandable for me by your code, the device ID which my driver callback, `ps_callback()`, receives contains only make and model, not the `CMD:` field with the PDLs, in my case I get `MFG:HP;MDL:OfficeJet Pro 8730;` for device URI `dnssd://HP%5C032OfficeJet%5C032Pro%5C0328730%5C032%5C09108C229%5C093._pdl-datastream._tcp.local/`. Your new code puts the componant into a `MFG:%s;MDL:%s;CMD:%s;` pattern, so I am wondering where this device ID actually comes from.
2. The way you generate the `CMD:` field from the `pdl` TXT record entry is too simple. It extracts only PostScript and PCL, you should extract as many PDLs as possible, in any combination: PDF, PCLXL, PCL5c, PCL5e, PCL3, PCL, JPEG, PCLM, AppleRaster, PWGRaster, ... at least the ones which have corresponding MIME types. Any of them can be useful for driver developers. My HP OfficeJet Pro 8730 has the following CMD entry: 
```
CMD:PCL5c,PCLXL,POSTSCRIPT,NATIVEOFFICE,PDF,PCL3GUI,PCL3,PJL,Automatic,JPEG,PCLM,AppleRaster,PWGRaster,802.11,802.3,DESKJET,DYN;
```

**Comment by tillkamppeter** [comment]
For (1) I have found the solution. You have made a buffer too small and the device ID got truncated, coincidentally exactly between MDL: and CMD: part.
This patch fixes it and makes the automatic model selection with my PostScript Printer Application work:
```
diff --git a/pappl/system-webif.c b/pappl/system-webif.c
index f790300..01dd86e 100644
--- a/pappl/system-webif.c
+++ b/pappl/system-webif.c
@@ -310,7 +310,7 @@ _papplSystemWebAddPrinter(
   const char   *status = NULL;         // Status message, if any
   char         printer_name[128] = "", // Printer Name
                driver_name[128] = "",  // Driver Name
-               device_uri[128] = "",   // Device URI
+               device_uri[1024] = "",  // Device URI
                *device_id = NULL,      // Device ID
                hostname[256] = "",     // Hostname
                *ptr;                   // Pointer into string
```
There is still a solution for (2) needed to improve cooperation with a wider range of Printer Applications.

**Comment by michaelrsweet** [comment]
@tillkamppeter First, *we do not need to support printers that support URF or PWG Raster*. Those are AirPrint/IPP Everywhere printers that are *already* supported directly.

Second, if the printer advertises the usb_CMD key in its TXT record, we'll use it. But otherwise we need to map MIME media types to 1284 command set names, of which PostScript and PCL have well-defined mappings. But many vendors (Brother, Canon, EPSON, and others) don't have MIME media types defined for their command sets and don't advertise either usb_CMD or a vendor type in the "pdl" key ("application/octet-stream" and "raw" are two common substitutes... 🙄)

I cannot invent values out of thin air. I absolutely *will not* add any kind of mapping table for the make and model. That is the job of the printer application, and if every printer with every connection type isn't able to be auto-added, *that isn't a failure*.

[master d994c6d] Enhance 1284 device ID support (Issue #73)

**Comment by michaelrsweet** [comment]
This commit contains the fix for the device URI buffer size:

[master cc4c979] Add a status message for when we can't add the printer because it already exists (Issue #86)
