### ISSUE TITLE
Handling of overwriting printers via "Add printer" broken

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#76]
**Describe the bug**
In the PostScript Printer Application I have created several printers to test it during its development. When I now add a new printer via the web interface and give it a queue name of an already existing printer, I do not get a warning that I am overwriting an existing printer, and in addition, a second printer with the same name gets created (see screenshot, "test4" and "test5" are duplicate. Such printers are not accessible separately and they could cause bad interferences, up to a crash (once I got a crash but currently I cannot reproduce it any more).

**To Reproduce**
Fire up a Printer Application and create a printer with the web interface, after that create again a printer with the web interface, using the name of the first printer. After that, the main page lists two printers with the same name.

**Expected behavior**
A warning that one uses a printer name which is already in use and telling the user to enter a different name.
To actually change the device and/or driver of an existing printer, the web interface should get an additional configuration page for the printers, reachable by a button in the printer entry, as we already have "Media" and "Printing defaults".

**Screenshots**
Duplicate printer entries "test4" and "test5":
![Duplicate entries](https://user-images.githubusercontent.com/1244825/99188691-93cc1780-275d-11eb-8d37-c7ba8997f09a.png)

**System Information:**
 - As usual, Ubuntu 20.10 Groovy and current GIT snapshots of PAPPL, cups-filters, and the PostScript Printer Application

**Comment by michaelrsweet** [comment]
@tillkamppeter There is no support for changing the device or driver of a printer - once set, you can't change it, and that is intentional. But the add printer interface should definitely protect against creating a duplicate printer.

**Comment by tillkamppeter** [comment]
I did not test, but the command line interface also should not accept a new printer with an already existing name.

**Comment by michaelrsweet** [comment]
[master 090ea34] Check whether a named printer already exists (Issue #76)
