### ISSUE TITLE
"OutputBin" option explicitly supported in `driver_data` but does not appear in web interface

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#77]
**Describe the bug**
I have a printer with several output bins to select from and these get listed in the `driver_data->bins` array, but in the web interface does not appear the output bin option to select one of them.

**To Reproduce**
In the PostScript Printer Application add a printer and select a model which has more than one output bin ("OutputBin" option in the PPD file used), then got to the Printer Defaults page. Here you see a lot of standard and vendor options but not output bin.
Hint: The Sharp AR-C260F PS has several output bins

**Expected behavior**
The output bin can be set in the web interface.

**Comment by michaelrsweet** [comment]
[master 168ef2d] Implement support for output-bin-default (Issue #77)

**Comment by tillkamppeter** [comment]
"OutputBin" is displayed now, but changing the setting is not saved. If I leave the "Printing Defaults" page and come back, the setting is back to the original default value. Also printing a job always uses the original default value.

**Comment by michaelrsweet** [comment]
@tillkamppeter The output-bin value wasn't even in the print options... Added, and proper support in `papplPrinterSetDriverDefaults` implemented...

[master 524703d] More "output-bin" issues resolved (Issue #77)
