### ISSUE TITLE
Web Interface: On "Printer Defaults" page you get a form submission error when changing too many settings at the same time

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#78]
**Describe the bug**
Withe the recent addition of vendor PPD option support in the PostScript Printer Application, a very long list of options can appear on the "Printer Defaults" page, especially for higher-end laser printers, like the Sharp AR-C260F PS, but the 8 vendor options of the HP OfficeJet Pro 8730 (an inkjet multi-function printer) are already enough to trigger this bug.
It is no problem to have a long option list. If one changes only one arbitrary option and submits the form, the option gets correctly changed (and the change saved in the state file), but if one changes all the vendor options and then submits the form one gets a form submission error. It looks like that the changes get added to a buffer and for changing all the options the buffer is too small.

**Comment by michaelrsweet** [comment]
@tillkamppeter Strange, the form read buffer is 64k and so shouldn't fill up so quickly. Can you provide a debug log from your printer application when trying to change the options?

Also, what browser are you using?

**Comment by tillkamppeter** [comment]
Browser is the Chromium which comes with Ubuntu 20.10 Groovy, version 85.0.4183.83.

**Comment by tillkamppeter** [comment]
I am not able to reproduce it any more, even with the Sharp where there are many more options.
