### ISSUE TITLE
When printing via the command line, vendor job options supplied via `-o` are ignored

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#79]
**Describe the bug**
After having started the PostScript Printer Application as a server I try to send a print job with the following command line:
```
ps-printer-app -d test -o collate=on -o print-color-as-gray=on -o rgb-color=photo-s-rgb -o secure-printing=on -o first-digit=5 -o second-digit=6 -o third-digit=7 -o fourth-digit=8 ~/ghostscript/testfiles/CityMap.pdf
```
The options are the vendor options for this printer. I have used the same option and choice names as they show in the web interface, on the "Printer Defaults" page. The job gets printed, but with the default settings as set in the web interface.

**To Reproduce**
Run the PostScript Printer Application as server, create a printer if you have not done so, then got to the "Printer Defaults" page of the web interface. Browse through the vendor options (the ones after the resolution line). Now send a job by running the PostScript Ptrinter Application as command line utility, with a command line similar to the above, with option and choice names as you have seen them in the web interface. Observe the printout (or the debug logging) and see that the changes by the options on the command line are not applied.

**Expected behavior**
Supplying options on the command line should work.

**Comment by michaelrsweet** [comment]
@tillkamppeter Please test the fix in master and let me know if it addresses your issue.

[master 43ac377] Fix vendor options at the command-line (Issue #79)

**Comment by tillkamppeter** [comment]
Unfortunately, it does not work for me, no crashes but the options get simply ignored. Attached is a debug log file of my server, with three jobs, "Job 1", "Job 2", and "Job 3". The printer is the HP OfficeJet Pro 8730, the print queue names "test" created via the web interface with driver auto-selection, using the DNS-SD device.
Here are the client command lines for the three jobs:

Job 1:
```
./ps-printer-app -d test ~/ghostscript/testfiles/CityMap.pdf
```
Job 2:
```
./ps-printer-app -d test -o print-color-as-gray=on ~/ghostscript/testfiles/CityMap.pdf
```
Job 3:
```
./ps-printer-app -d test -o collate=on -o print-color-as-gray=on -o rgb-color=vivid-s-rgb -o secure-printing=on -o first-digit=1 -o second-digit=2 -o third-digit=3 -o fourth-digit=4 ~/ghostscript/testfiles/CityMap.pdf
```
Here is the log file:
[vendor-options-on-command-line-1.txt](https://github.com/michaelrsweet/pappl/files/5612709/vendor-options-on-command-line-1.txt)
Here is a screen shot which shows the available vendor options:
![Screenshot from 2020-11-29 20-10-59](https://user-images.githubusercontent.com/1244825/100551334-11287980-3280-11eb-8b60-f776512ca9a0.png)

**Comment by michaelrsweet** [comment]
OK, I think I have it now (and verified via testmainloop unit test program):

[master 2cf98d8] Fix vendor options - wrong logic for ignoring standard options...

**Comment by tillkamppeter** [comment]
Now it works, thank you very much.
