### ISSUE TITLE
In the TXT record of the DNS-SD broadcast of an emulated IPP printer "pdl" is "("

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#8]
I have run testpappl to try out the Printer Application framework. The test setup emulates two IPP printers. I can create CUPS queues using
```
lpadmin -p printer -E -v URI -m everywhere
```
and print on these queues, but I do not get any auto discovery of these printers, for example by the `driverless` utility or by `cups-browsed` from cups-filters. In the output of `avahi-discover` (or `avahi-browse`)  I have seen thst tha PDL entry in the TXT record of the emulated printers is broken, and auto-discovery tools like `driverless` or `cups-browsed` identify driverless-capable IPP printers by the PDLs which get advertised for them. The "pdl" field in the TXT record is always simply "(" which does not make sense. It looks like that some pointer is pointing to something wrong.

**Comment by tillkamppeter** [comment]
All done with Ubuntu 20.04 Focal, CUPS 2.3.1, cups-filters 1.27.3.

**Comment by michaelrsweet** [comment]
I think I have this fixed (keep in mind things are still in flux as I get everything hooked up...)
