### ISSUE TITLE
SNMP supply level query function

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#83]
**Describe the solution you'd like**
Most IPP- or SNMP-capable printers allow for standardized ways to poll their ink levels, independent of PDL in use. CUPS makes use of this by (probably all) its backends polling ink levels on each job and dropping them into `error_log`. As this works for many printers independent of their PDL it would be great if appropriate functions (one for IPP, one for SNMP) get added to PAPPL so that one does not need to re-implement this in every Printer Application. 
The Printer Application could call this out of the status callback and the levels could be displayed on the main page and the printer pages of the web interface and also be passed on when a client polls ink levels vis IPP.

**Comment by michaelrsweet** [comment]
I won't do IPP queries because PAPPL doesn't support IPP printers (not much point, IPP printers with sufficient capabilities are supported directly by CUPS) but I could add an SNMP query function that populated the pappl_supply_t structure.

**Comment by tillkamppeter** [comment]
OK, let us go this way.
