### ISSUE TITLE
Driver-specific extensions of the web interface

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#84]
**Describe the solution you'd like**
Sometimes there is printer- or driver-specific functionality which cannot be necessarily described by extra options ("vendor options") on the "Printer Defaults" page.

For PostScript for example there are:
1. For (nearly) each option there is PostScript code in the PPD file with which one can poll the setting of the option from the printer.
2. In the PPD file is a group of options (usually named "Installable Options") with which one can tell which optional accessories (like extra trays, mail boxes, duplex unit, ...) are installed in the printer. UI constraints describe which choices of the actual job options (the ones to be listed on the "Printer Defaults" page) are available and which not depending on whether the accessory is installed or not. Sometimes there is even PostScript code so that one can apply (1) to auto-detect the printer's hardware configuration.

I have now thought about how one can make use of this functionality. Without any changes on the web interface it is rather restricted, one could poll the printer for option default settings and installed accessories when one creates the queue for it, but
- The printer gets woken up (for PostScript the poll is a zero-page PostScript job sending back the settings as answer) on driver setup (creation of the queue and every start of the Printer Application)
- The poll cannot get easily repeated when accessories are added/removed or printer-internal defaults changed. Having to restart the Printer Application is no very intuitive and in the previous point we also told that we do not have a poll during startup.
- With the options of the "Installable Options" group on the "Printer Defaults" page together with the job options one would need to modify settings of one option when the setting of another is changed which gets difficult on web forms.

So what I need would be driver-specific customizations of the web interface. For the PostScript Printer Application this would be:
- The print queue pages (and also the printer entries on the main page) have one extra button, named "Installable Options". This button opens a page which shows all the options of the "Installable Options" group of the PPD file. When submitting the settings, the driver setup callback is re-run, taking into a account these settings by not adding the conflicting choices of the options to the driver data structure. The "Installable Options" page could in addition have a button which, when one clicks on it, triggers the printer being polled for the settings of all the "Installable Options".
- The "Printer Defaults" (and also "Media") have an extra button to poll the value from the printer. The page also has an extra button to poll all the option values.

So what I would like to have that there are callback functions which allow to add extra buttons to print queue entries and to pages like "Media" and "Printer Defaults", ideally also to each option. I also would like to have the possibility to add extra configuration pages to the print queues.

**Comment by michaelrsweet** [comment]
@tillkamppeter You can add custom web pages with `papplSystemAddResourceCallback` and add links with `papplPrinterAddLink`.

That said, ordinarily this is something that the status callback is supposed to do automatically. What I would suggest is to query the installable options once per minute (or every five minutes), keeping track of the last time you checked since PAPPL will call you up to once per second.
