### ISSUE TITLE
Web Interface: Show boolean options as check box

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#85]
If a vendor option is boolean, as "vendor-boolean" of the "Label Printer" in the example Printer Application of PAPPL (see screen shot), the web interface should not show a drop-down of the two choices "true" and "false" but, instead, a check box, with checked meaning true and unchecked meaning false.

This is much more user-friendly than showing "true" and "false" to not programming-aware users.

![Screenshot from 2020-11-22 22-42-10](https://user-images.githubusercontent.com/1244825/99918611-5eed3100-2d18-11eb-9de9-2aff964fde01.png)

**Comment by michaelrsweet** [comment]
[master 2b5273c] Fix boolean options to use checkbox (Issue #85)

**Comment by tillkamppeter** [comment]
Thanks, is displayed correctly now, but does not actually work.
If I check the box and click the button to save my changes the box gets unchecked again, also if I leave the "Printing Defaults" and come back later, the box is always unchecked.

**Comment by michaelrsweet** [comment]
[master e06079e] Fix checkbox - "on" not "checked" for set value (Issue #85)
