### ISSUE TITLE
Web Interface: No feedback why printer does not get added

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#86]
**Describe the bug**
On the "Add Printer" page the user selects a discovered printer and a driver for it. Then the driver callback (in the PostScript Printer Application this is `ps_callback()` is called to initialize the driver (populate `driver_data`) for this printer.

In some cases (for the PostScript Printer Application selecting "Automatic Selection" for the model and the printer not supporting PostScript) the driver callback fails and returns `false`. Assuming nothing is broken with the Printer Application this should happen when the discovered printer selected is not supported by this Printer Application.

The web interface in such a case resets the user input (queue name, device, and driver selection) in the web form and shows the web form again, without any message what was wrong. This is not a very user-friendly behavior.

**To Reproduce**
Start the PostScript Printer Application. Under the discovered printers choose one which does not support PostScript and as driver choose "Automatic Selection". Submit the form. Instead of any message telling that the printer is not supported the form will show again, empty, with a delay due to the fact that the printer discovery in the network gets repeated.

**Expected behavior**
When submitting the form with the unsupported printer, the form should immediately re-appear with the user's input conserved (so that he can easily correct, like choosing another discovered printer) and at the top an error message, telling that the printer is not supported.

**Comment by michaelrsweet** [comment]
[master cc4c979] Add a status message for when we can't add the printer because it already exists (Issue #86)

**Comment by tillkamppeter** [comment]
Thanks, for the case of entering a duplicate queue name this is OK, but for me the message that the queue name is duplicate also appears when the driver callback exited with "false" (printer not supported by driver). In this case an appropriate status message should appear and also the queue name should stay in the input field.

In addition, on a failure to add the new print queue and therefore re-display of the "Add Printer" page the discovery should not get repeated but the discovered printer list from the previous dispaly of the page being used, to avoid the delay.

**Comment by michaelrsweet** [comment]
@tillkamppeter WRT the delay, this is a simple POST form and not a web service with a JavaScript front-end. The device re-discovery delay cannot be avoided.

I will see what I can do to propagate the printer creation error (also useful for the IPP interface).

**Comment by michaelrsweet** [comment]
[master 0ded5dc] Provide more information about printer creation failures (Issue #86)
[master 6ea9357] Include unsupported attributes on Create-Printer errors, map driver error to client-error-attributes-or-values-not-supported (Issue #86)

**Comment by michaelrsweet** [comment]
@tillkamppeter Let me know if there is anything else I need to address for this issue.

**Comment by tillkamppeter** [comment]
Much better now, but another little UX improvement:

Please do not remove the offending input when re-displaying the "printing Defaults" page, most probably it is an "off by one", for example you have "My Great Printer 1" and want to create "My Great Printer 2" but mis-type the number in the end. Would be nice if you only need to edit the number instead of typing "My Great Printer" again.
Also for the driver selection, if you have chosen the wrong of the ~4000 entries, the right being the one before or after the one you have accidentally chose, it is much easier having the list on the wrong entry and you only need to correct one up or down instead of weeding through the list again. And you get remembered what was the wrong one so that you choose another now and not accidentally the wrong one again (user falls into infinite loop)..

**Comment by michaelrsweet** [comment]
@tillkamppeter Fair enough:

[master 41eaf36] Don't clear selection/entry on error (Issue #86)

**Comment by tillkamppeter** [comment]
Another point: Do not let the error messages fade out (on all pages), if the user does not read quck enough, especially turns away from the screen when the re-display takes some time due to the re-discovery.

**Comment by michaelrsweet** [comment]
@tillkamppeter I still want to fade the errors a little (so that you know it isn't a new error), but I can change the transition so that they are still visible.

**Comment by tillkamppeter** [comment]
OK, let us go this way.

**Comment by michaelrsweet** [comment]
[master acdfbb7] Change the banner animation to go from the colored background to gray - that way the errors are still visible but you know they aren't new (Issue #86)

**Comment by tillkamppeter** [comment]
Works great now, thanks.
