### ISSUE TITLE
Any printer driver name is treated as "auto", including existing ones

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#88]
**Describe the bug**
See this piece of code in the `papplPrinterCreate()` function:
```
  // If the driver is "auto", figure out the proper driver name...
  if ((driver_name = (system->autoadd_cb)(printer_name, device_uri, device_id, system->driver_cbdata)) == NULL)
  {
    errno = EIO;
    _papplPrinterDelete(printer);
    return (NULL);
  }
```
The content of `driver_name` is nowhere checked but simply the auto-add callback called.

**Expected behavior**
See issue #87.

**Comment by michaelrsweet** [comment]
[master 968df43] Don't auto-add everything... (Issue #88)
