### ISSUE TITLE
Callback for papplPrinterCreate() to add extra features

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#90]
**Describe the solution you'd like**
In the PostScript Printer Application I want each printer to have an extra page in its web interface and an appropriate button in the printer entries on the front page and also on the printer's main pages. The page would be to allow setting the "Installable Options" of the PPD file.
The standard web pages are added in the `papplPrinterCreate()` function. For my page I would have to add code like this:
```
    snprintf(path, sizeof(path), "%s/installable", printer->uriname);
    papplSystemAddResourceCallback(system, path, "text/html", (pappl_resource_cb_t)ps_printer_web_installable, printer);
    papplPrinterAddLink(printer, "Installable Options", path, true);
```
I only do not know where I have to add this code. Is there actually a place for such additions?

If not, I suggest the addition of a callback function call to the end of the `papplPrinterCreate()` right before the completed `printer` data structure being returned.

**Comment by michaelrsweet** [comment]
[master f501a45] Add a printer creation callback (Issue #90)
