### ISSUE TITLE
Printer: I can only add items to the top bar, not to the buttons on the page

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/pappl#98]
I have added the following printer creation callback function to the PostScript Printer Applications:
```
static void   ps_printer_extra_setup(pappl_printer_t *printer,
				     void *data)
{
  char                  path[256];      // Path to resource

  //snprintf(path, sizeof(path), "%s/getdefaults", printer->uriname);
  snprintf(path, sizeof(path), "/ipp/printers/%s/getdefaults",
	   papplPrinterGetName(printer));
  //papplSystemAddResourceCallback(system, path, "text/html",
  //			       (pappl_resource_cb_t)ps_printer_web_get_defaults,
  //			       printer);
  papplPrinterAddLink(printer, "Defaults from Printer", path, true);

  //snprintf(path, sizeof(path), "%s/installable", printer->uriname);
  snprintf(path, sizeof(path), "/ipp/printers/%s/installable",
	   papplPrinterGetName(printer));
  //papplSystemAddResourceCallback(system, path, "text/html",
  //			       (pappl_resource_cb_t)ps_printer_web_installable,
  //			       printer);
  papplPrinterAddLink(printer, "Installable Options", path, true);
}
```
There are several lines commented out, as I did not write the code for the extra web interface pages yet and also issue #97 is not solved yet (so the way to create the paths is most probably wrong for now).
The few active lines (the `papplPrinterAddLink()`calls) create items in the individual printer's web interfaces, but only on the printer's pages (not in the printer entries on the system's main page) and only in the top bar. For a consistent user interface I would like to add these items also to the buttons of both the printer's page and the printer entry in the system's main page.
Is this possible? If not, I appreciate the addtion of an extra function which does exactly this and which I could add to te above function.

**Screenshot**
![Screenshot from 2020-12-03 21-59-59](https://user-images.githubusercontent.com/1244825/101089228-2cafbf00-35b5-11eb-88c2-4ac66f87d0d1.png)
Here one sees the items "Defaults from Printer" and "Installable Options" in the black top bar but not under the buttons near the icon.

**Comment by michaelrsweet** [comment]
OK, I have updated `papplPrinterAddLink` and `papplSystemAddLink` to use a enum bitfield that specifies where the links are shown, in addition to the old HTTPS option. This gets used in most places to insert buttons as needed (with three exceptions: supply levels, identification, and test page since those depend on the current printer driver data...)

[master 17896d4] Update papplPrinter/SystemAddLink to accept an options bitfield (Issue #98)
